var annotated_dup =
[
    [ "GCKAdBreakClipInfo", "interface_g_c_k_ad_break_clip_info.html", "interface_g_c_k_ad_break_clip_info" ],
    [ "GCKAdBreakClipVastAdsRequest", "interface_g_c_k_ad_break_clip_vast_ads_request.html", "interface_g_c_k_ad_break_clip_vast_ads_request" ],
    [ "GCKAdBreakInfo", "interface_g_c_k_ad_break_info.html", "interface_g_c_k_ad_break_info" ],
    [ "GCKAdBreakStatus", "interface_g_c_k_ad_break_status.html", "interface_g_c_k_ad_break_status" ],
    [ "GCKApplicationMetadata", "interface_g_c_k_application_metadata.html", "interface_g_c_k_application_metadata" ],
    [ "GCKCastChannel", "interface_g_c_k_cast_channel.html", "interface_g_c_k_cast_channel" ],
    [ "GCKCastContext", "interface_g_c_k_cast_context.html", "interface_g_c_k_cast_context" ],
    [ "<GCKCastDeviceStatusListener >", "protocol_g_c_k_cast_device_status_listener_01-p.html", "protocol_g_c_k_cast_device_status_listener_01-p" ],
    [ "GCKCastOptions", "interface_g_c_k_cast_options.html", "interface_g_c_k_cast_options" ],
    [ "GCKCastSession", "interface_g_c_k_cast_session.html", "interface_g_c_k_cast_session" ],
    [ "GCKColor", "interface_g_c_k_color.html", "interface_g_c_k_color" ],
    [ "GCKDevice", "interface_g_c_k_device.html", "interface_g_c_k_device" ],
    [ "GCKDeviceProvider", "interface_g_c_k_device_provider.html", "interface_g_c_k_device_provider" ],
    [ "GCKDeviceProvider(Protected)", "category_g_c_k_device_provider_07_protected_08.html", "category_g_c_k_device_provider_07_protected_08" ],
    [ "GCKDiscoveryCriteria", "interface_g_c_k_discovery_criteria.html", "interface_g_c_k_discovery_criteria" ],
    [ "GCKDiscoveryManager", "interface_g_c_k_discovery_manager.html", "interface_g_c_k_discovery_manager" ],
    [ "<GCKDiscoveryManagerListener >", "protocol_g_c_k_discovery_manager_listener_01-p.html", "protocol_g_c_k_discovery_manager_listener_01-p" ],
    [ "GCKError", "interface_g_c_k_error.html", "interface_g_c_k_error" ],
    [ "GCKGenericChannel", "interface_g_c_k_generic_channel.html", "interface_g_c_k_generic_channel" ],
    [ "<GCKGenericChannelDelegate >", "protocol_g_c_k_generic_channel_delegate_01-p.html", "protocol_g_c_k_generic_channel_delegate_01-p" ],
    [ "GCKImage", "interface_g_c_k_image.html", "interface_g_c_k_image" ],
    [ "GCKJSONUtils", "interface_g_c_k_j_s_o_n_utils.html", "interface_g_c_k_j_s_o_n_utils" ],
    [ "GCKLaunchOptions", "interface_g_c_k_launch_options.html", "interface_g_c_k_launch_options" ],
    [ "GCKLogger", "interface_g_c_k_logger.html", "interface_g_c_k_logger" ],
    [ "<GCKLoggerDelegate >", "protocol_g_c_k_logger_delegate_01-p.html", "protocol_g_c_k_logger_delegate_01-p" ],
    [ "GCKLoggerFilter", "interface_g_c_k_logger_filter.html", "interface_g_c_k_logger_filter" ],
    [ "GCKMediaInformation", "interface_g_c_k_media_information.html", "interface_g_c_k_media_information" ],
    [ "GCKMediaInformationBuilder", "interface_g_c_k_media_information_builder.html", "interface_g_c_k_media_information_builder" ],
    [ "GCKMediaLoadOptions", "interface_g_c_k_media_load_options.html", "interface_g_c_k_media_load_options" ],
    [ "GCKMediaMetadata", "interface_g_c_k_media_metadata.html", "interface_g_c_k_media_metadata" ],
    [ "GCKMediaQueueItem", "interface_g_c_k_media_queue_item.html", "interface_g_c_k_media_queue_item" ],
    [ "GCKMediaQueueItemBuilder", "interface_g_c_k_media_queue_item_builder.html", "interface_g_c_k_media_queue_item_builder" ],
    [ "GCKMediaQueueLoadOptions", "interface_g_c_k_media_queue_load_options.html", "interface_g_c_k_media_queue_load_options" ],
    [ "GCKMediaRequestItem", "interface_g_c_k_media_request_item.html", "interface_g_c_k_media_request_item" ],
    [ "GCKMediaSeekOptions", "interface_g_c_k_media_seek_options.html", "interface_g_c_k_media_seek_options" ],
    [ "GCKMediaStatus", "interface_g_c_k_media_status.html", "interface_g_c_k_media_status" ],
    [ "GCKMediaTextTrackStyle", "interface_g_c_k_media_text_track_style.html", "interface_g_c_k_media_text_track_style" ],
    [ "GCKMediaTrack", "interface_g_c_k_media_track.html", "interface_g_c_k_media_track" ],
    [ "GCKMultizoneDevice", "interface_g_c_k_multizone_device.html", "interface_g_c_k_multizone_device" ],
    [ "GCKMultizoneStatus", "interface_g_c_k_multizone_status.html", "interface_g_c_k_multizone_status" ],
    [ "GCKNetworkAddress", "interface_g_c_k_network_address.html", "interface_g_c_k_network_address" ],
    [ "GCKOpenURLOptions", "interface_g_c_k_open_u_r_l_options.html", "interface_g_c_k_open_u_r_l_options" ],
    [ "GCKRemoteMediaClient", "interface_g_c_k_remote_media_client.html", "interface_g_c_k_remote_media_client" ],
    [ "GCKRemoteMediaClient(Protected)", "category_g_c_k_remote_media_client_07_protected_08.html", "category_g_c_k_remote_media_client_07_protected_08" ],
    [ "<GCKRemoteMediaClientAdInfoParserDelegate >", "protocol_g_c_k_remote_media_client_ad_info_parser_delegate_01-p.html", "protocol_g_c_k_remote_media_client_ad_info_parser_delegate_01-p" ],
    [ "<GCKRemoteMediaClientListener >", "protocol_g_c_k_remote_media_client_listener_01-p.html", "protocol_g_c_k_remote_media_client_listener_01-p" ],
    [ "GCKRequest", "interface_g_c_k_request.html", "interface_g_c_k_request" ],
    [ "<GCKRequestDelegate >", "protocol_g_c_k_request_delegate_01-p.html", "protocol_g_c_k_request_delegate_01-p" ],
    [ "GCKSenderApplicationInfo", "interface_g_c_k_sender_application_info.html", "interface_g_c_k_sender_application_info" ],
    [ "GCKSession", "interface_g_c_k_session.html", "interface_g_c_k_session" ],
    [ "GCKSession(Protected)", "category_g_c_k_session_07_protected_08.html", "category_g_c_k_session_07_protected_08" ],
    [ "GCKSessionManager", "interface_g_c_k_session_manager.html", "interface_g_c_k_session_manager" ],
    [ "<GCKSessionManagerListener >", "protocol_g_c_k_session_manager_listener_01-p.html", "protocol_g_c_k_session_manager_listener_01-p" ],
    [ "GCKSessionTraits", "interface_g_c_k_session_traits.html", "interface_g_c_k_session_traits" ],
    [ "GCKVideoInfo", "interface_g_c_k_video_info.html", "interface_g_c_k_video_info" ],
    [ "NSDictionary(GCKAdditions)", "category_n_s_dictionary_07_g_c_k_additions_08.html", "category_n_s_dictionary_07_g_c_k_additions_08" ],
    [ "NSMutableDictionary(GCKAdditions)", "category_n_s_mutable_dictionary_07_g_c_k_additions_08.html", "category_n_s_mutable_dictionary_07_g_c_k_additions_08" ],
    [ "NSTimer(GCKAdditions)", "category_n_s_timer_07_g_c_k_additions_08.html", "category_n_s_timer_07_g_c_k_additions_08" ],
    [ "OOCastManager", "interface_o_o_cast_manager.html", "interface_o_o_cast_manager" ],
    [ "OOCastManager(GCKSessionManagerListener)", "category_o_o_cast_manager_07_g_c_k_session_manager_listener_08.html", "category_o_o_cast_manager_07_g_c_k_session_manager_listener_08" ],
    [ "<OOCastManagerDelegate>", "protocol_o_o_cast_manager_delegate-p.html", "protocol_o_o_cast_manager_delegate-p" ],
    [ "<OOCastManagerInternalProtocol >", "protocol_o_o_cast_manager_internal_protocol_01-p.html", "protocol_o_o_cast_manager_internal_protocol_01-p" ],
    [ "<OOCastMiniControllerDelegate >", "protocol_o_o_cast_mini_controller_delegate_01-p.html", "protocol_o_o_cast_mini_controller_delegate_01-p" ],
    [ "<OOCastMiniControllerProtocol >", "protocol_o_o_cast_mini_controller_protocol_01-p.html", "protocol_o_o_cast_mini_controller_protocol_01-p" ],
    [ "OOCastMiniControllerView", "interface_o_o_cast_mini_controller_view.html", "interface_o_o_cast_mini_controller_view" ],
    [ "OOCastPlayer", "interface_o_o_cast_player.html", "interface_o_o_cast_player" ],
    [ "OOCastPlayer(GCKRemoteMediaClientListener)", "category_o_o_cast_player_07_g_c_k_remote_media_client_listener_08.html", "category_o_o_cast_player_07_g_c_k_remote_media_client_listener_08" ],
    [ "OOCastReceiverResponseManager", "interface_o_o_cast_receiver_response_manager.html", "interface_o_o_cast_receiver_response_manager" ]
];