var namespacecom_1_1ooyala_1_1android_1_1skin_1_1notification_1_1provider =
[
    [ "AudioNotificationHandlersProvider", "classcom_1_1ooyala_1_1android_1_1skin_1_1notification_1_1provider_1_1_audio_notification_handlers_provider.html", "classcom_1_1ooyala_1_1android_1_1skin_1_1notification_1_1provider_1_1_audio_notification_handlers_provider" ],
    [ "NotificationHandlersProvider", "interfacecom_1_1ooyala_1_1android_1_1skin_1_1notification_1_1provider_1_1_notification_handlers_provider.html", "interfacecom_1_1ooyala_1_1android_1_1skin_1_1notification_1_1provider_1_1_notification_handlers_provider" ],
    [ "VideoNotificationHandlersProvider", "classcom_1_1ooyala_1_1android_1_1skin_1_1notification_1_1provider_1_1_video_notification_handlers_provider.html", "classcom_1_1ooyala_1_1android_1_1skin_1_1notification_1_1provider_1_1_video_notification_handlers_provider" ]
];