var annotated_dup =
[
    [ "GCKApplicationMetadata", "interface_g_c_k_application_metadata.html", "interface_g_c_k_application_metadata" ],
    [ "GCKCastChannel", "interface_g_c_k_cast_channel.html", "interface_g_c_k_cast_channel" ],
    [ "GCKCastContext", "interface_g_c_k_cast_context.html", "interface_g_c_k_cast_context" ],
    [ "GCKColor", "interface_g_c_k_color.html", "interface_g_c_k_color" ],
    [ "GCKDevice", "interface_g_c_k_device.html", "interface_g_c_k_device" ],
    [ "GCKDeviceManager", "interface_g_c_k_device_manager.html", "interface_g_c_k_device_manager" ],
    [ "<GCKDeviceManagerDelegate >", "protocol_g_c_k_device_manager_delegate_01-p.html", "protocol_g_c_k_device_manager_delegate_01-p" ],
    [ "GCKDeviceScanner", "interface_g_c_k_device_scanner.html", "interface_g_c_k_device_scanner" ],
    [ "<GCKDeviceScannerListener >", "protocol_g_c_k_device_scanner_listener_01-p.html", "protocol_g_c_k_device_scanner_listener_01-p" ],
    [ "GCKError", "interface_g_c_k_error.html", "interface_g_c_k_error" ],
    [ "GCKFilterCriteria", "interface_g_c_k_filter_criteria.html", "interface_g_c_k_filter_criteria" ],
    [ "GCKGenericChannel", "interface_g_c_k_generic_channel.html", "interface_g_c_k_generic_channel" ],
    [ "<GCKGenericChannelDelegate >", "protocol_g_c_k_generic_channel_delegate_01-p.html", "protocol_g_c_k_generic_channel_delegate_01-p" ],
    [ "GCKImage", "interface_g_c_k_image.html", "interface_g_c_k_image" ],
    [ "GCKJSONUtils", "interface_g_c_k_j_s_o_n_utils.html", "interface_g_c_k_j_s_o_n_utils" ],
    [ "GCKLaunchOptions", "interface_g_c_k_launch_options.html", "interface_g_c_k_launch_options" ],
    [ "GCKLogger", "interface_g_c_k_logger.html", "interface_g_c_k_logger" ],
    [ "<GCKLoggerDelegate>", "protocol_g_c_k_logger_delegate-p.html", "protocol_g_c_k_logger_delegate-p" ],
    [ "GCKMediaControlChannel", "interface_g_c_k_media_control_channel.html", "interface_g_c_k_media_control_channel" ],
    [ "<GCKMediaControlChannelDelegate >", "protocol_g_c_k_media_control_channel_delegate_01-p.html", "protocol_g_c_k_media_control_channel_delegate_01-p" ],
    [ "GCKMediaInformation", "interface_g_c_k_media_information.html", "interface_g_c_k_media_information" ],
    [ "GCKMediaMetadata", "interface_g_c_k_media_metadata.html", "interface_g_c_k_media_metadata" ],
    [ "GCKMediaQueueItem", "interface_g_c_k_media_queue_item.html", "interface_g_c_k_media_queue_item" ],
    [ "GCKMediaQueueItemBuilder", "interface_g_c_k_media_queue_item_builder.html", "interface_g_c_k_media_queue_item_builder" ],
    [ "GCKMediaStatus", "interface_g_c_k_media_status.html", "interface_g_c_k_media_status" ],
    [ "GCKMediaTextTrackStyle", "interface_g_c_k_media_text_track_style.html", "interface_g_c_k_media_text_track_style" ],
    [ "GCKMediaTrack", "interface_g_c_k_media_track.html", "interface_g_c_k_media_track" ],
    [ "GCKSenderApplicationInfo", "interface_g_c_k_sender_application_info.html", "interface_g_c_k_sender_application_info" ],
    [ "NSDictionary(GCKAdditions)", "category_n_s_dictionary_07_g_c_k_additions_08.html", "category_n_s_dictionary_07_g_c_k_additions_08" ],
    [ "OOCastButton", "interface_o_o_cast_button.html", "interface_o_o_cast_button" ],
    [ "OOCastManager", "interface_o_o_cast_manager.html", "interface_o_o_cast_manager" ],
    [ "OOCastManager(Intenal)", "category_o_o_cast_manager_07_intenal_08.html", "category_o_o_cast_manager_07_intenal_08" ],
    [ "OOCastManager(Internal)", "category_o_o_cast_manager_07_internal_08.html", "category_o_o_cast_manager_07_internal_08" ],
    [ "<OOCastManagerDelegate>", "protocol_o_o_cast_manager_delegate-p.html", "protocol_o_o_cast_manager_delegate-p" ],
    [ "OOCastManagerDeviceReconnector", "interface_o_o_cast_manager_device_reconnector.html", "interface_o_o_cast_manager_device_reconnector" ],
    [ "OOCastMenuViewController", "interface_o_o_cast_menu_view_controller.html", "interface_o_o_cast_menu_view_controller" ],
    [ "<OOCastMiniControllerDelegate >", "protocol_o_o_cast_mini_controller_delegate_01-p.html", "protocol_o_o_cast_mini_controller_delegate_01-p" ],
    [ "<OOCastMiniControllerProtocol >", "protocol_o_o_cast_mini_controller_protocol_01-p.html", "protocol_o_o_cast_mini_controller_protocol_01-p" ],
    [ "OOCastMiniControllerView", "interface_o_o_cast_mini_controller_view.html", "interface_o_o_cast_mini_controller_view" ],
    [ "OOCastPlayer", "interface_o_o_cast_player.html", "interface_o_o_cast_player" ],
    [ "OOCastUtils", "interface_o_o_cast_utils.html", "interface_o_o_cast_utils" ]
];