var annotated_dup =
[
    [ "_OOTBXMLAttribute", "struct___o_o_t_b_x_m_l_attribute.html", "struct___o_o_t_b_x_m_l_attribute" ],
    [ "_OOTBXMLAttributeBuffer", "struct___o_o_t_b_x_m_l_attribute_buffer.html", "struct___o_o_t_b_x_m_l_attribute_buffer" ],
    [ "_OOTBXMLElement", "struct___o_o_t_b_x_m_l_element.html", "struct___o_o_t_b_x_m_l_element" ],
    [ "_OOTBXMLElementBuffer", "struct___o_o_t_b_x_m_l_element_buffer.html", "struct___o_o_t_b_x_m_l_element_buffer" ],
    [ "MediaCodecUtils", "interface_media_codec_utils.html", "interface_media_codec_utils" ],
    [ "NSData(NSDataAdditions)", "category_n_s_data_07_n_s_data_additions_08.html", "category_n_s_data_07_n_s_data_additions_08" ],
    [ "OOAdOverlayInfo", "interface_o_o_ad_overlay_info.html", "interface_o_o_ad_overlay_info" ],
    [ "<OOAdPlugin>", "protocol_o_o_ad_plugin-p.html", "protocol_o_o_ad_plugin-p" ],
    [ "<OOAdPluginManagerProtocol>", "protocol_o_o_ad_plugin_manager_protocol-p.html", "protocol_o_o_ad_plugin_manager_protocol-p" ],
    [ "OOAdPodInfo", "interface_o_o_ad_pod_info.html", "interface_o_o_ad_pod_info" ],
    [ "OOAdsLearnMoreButton", "class_o_o_ads_learn_more_button.html", null ],
    [ "OOAdSpot", "interface_o_o_ad_spot.html", "interface_o_o_ad_spot" ],
    [ "OOAdSpotManager", "interface_o_o_ad_spot_manager.html", "interface_o_o_ad_spot_manager" ],
    [ "OOAdSpotPlugin", "interface_o_o_ad_spot_plugin.html", "interface_o_o_ad_spot_plugin" ],
    [ "<OOAdSpotPluginDelegate>", "protocol_o_o_ad_spot_plugin_delegate-p.html", "protocol_o_o_ad_spot_plugin_delegate-p" ],
    [ "OOAirPlayButton", "interface_o_o_air_play_button.html", null ],
    [ "OOAnalyticsPluginBaseImpl", "interface_o_o_analytics_plugin_base_impl.html", null ],
    [ "<OOAnalyticsPluginProtocol >", "protocol_o_o_analytics_plugin_protocol_01-p.html", "protocol_o_o_analytics_plugin_protocol_01-p" ],
    [ "OOAssetDownloadManager", "interface_o_o_asset_download_manager.html", "interface_o_o_asset_download_manager" ],
    [ "OOAssetDownloadOptions", "interface_o_o_asset_download_options.html", "interface_o_o_asset_download_options" ],
    [ "OOAssetDownloadStream", "interface_o_o_asset_download_stream.html", "interface_o_o_asset_download_stream" ],
    [ "OOAssetLoaderDelegate", "interface_o_o_asset_loader_delegate.html", "interface_o_o_asset_loader_delegate" ],
    [ "OOAssetStore", "interface_o_o_asset_store.html", "interface_o_o_asset_store" ],
    [ "OOAudioTrack", "interface_o_o_audio_track.html", "interface_o_o_audio_track" ],
    [ "<OOAudioTrackProtocol >", "protocol_o_o_audio_track_protocol_01-p.html", "protocol_o_o_audio_track_protocol_01-p" ],
    [ "<OOAudioTrackSelectionProtocol >", "protocol_o_o_audio_track_selection_protocol_01-p.html", "protocol_o_o_audio_track_selection_protocol_01-p" ],
    [ "<OOAuthorizableItem >", "protocol_o_o_authorizable_item_01-p.html", "protocol_o_o_authorizable_item_01-p" ],
    [ "OOBufferView", "interface_o_o_buffer_view.html", "interface_o_o_buffer_view" ],
    [ "OOCaption", "interface_o_o_caption.html", "interface_o_o_caption" ],
    [ "<OOCastManagerProtocol >", "protocol_o_o_cast_manager_protocol_01-p.html", "protocol_o_o_cast_manager_protocol_01-p" ],
    [ "OOCastModeOptions", "interface_o_o_cast_mode_options.html", "interface_o_o_cast_mode_options" ],
    [ "OOChannel", "interface_o_o_channel.html", "interface_o_o_channel" ],
    [ "OOChannelSet", "interface_o_o_channel_set.html", "interface_o_o_channel_set" ],
    [ "OOClientId", "interface_o_o_client_id.html", "interface_o_o_client_id" ],
    [ "OOClosedCaptions", "interface_o_o_closed_captions.html", "interface_o_o_closed_captions" ],
    [ "OOClosedCaptionsButton", "interface_o_o_closed_captions_button.html", null ],
    [ "OOClosedCaptionsItem", "interface_o_o_closed_captions_item.html", "interface_o_o_closed_captions_item" ],
    [ "OOClosedCaptionsLabel", "interface_o_o_closed_captions_label.html", "interface_o_o_closed_captions_label" ],
    [ "OOClosedCaptionsSelectorBackgroundViewController", "interface_o_o_closed_captions_selector_background_view_controller.html", "interface_o_o_closed_captions_selector_background_view_controller" ],
    [ "OOClosedCaptionsSelectorViewController", "interface_o_o_closed_captions_selector_view_controller.html", "interface_o_o_closed_captions_selector_view_controller" ],
    [ "OOClosedCaptionsStyle", "interface_o_o_closed_captions_style.html", "interface_o_o_closed_captions_style" ],
    [ "OOClosedCaptionsView", "interface_o_o_closed_captions_view.html", "interface_o_o_closed_captions_view" ],
    [ "OOContentItem", "interface_o_o_content_item.html", "interface_o_o_content_item" ],
    [ "OOControlsViewController", "interface_o_o_controls_view_controller.html", "interface_o_o_controls_view_controller" ],
    [ "OOCuePointsView", "interface_o_o_cue_points_view.html", "interface_o_o_cue_points_view" ],
    [ "<OOCuePointViewDurationDataSource>", "protocol_o_o_cue_point_view_duration_data_source-p.html", "protocol_o_o_cue_point_view_duration_data_source-p" ],
    [ "OODebugMode", "interface_o_o_debug_mode.html", "interface_o_o_debug_mode" ],
    [ "OODefaultAudioOnlyPlayerInfo", "interface_o_o_default_audio_only_player_info.html", null ],
    [ "OODefaultPlayerInfo", "interface_o_o_default_player_info.html", null ],
    [ "OODeviceInfo", "interface_o_o_device_info.html", "interface_o_o_device_info" ],
    [ "OODiscoveryManager", "interface_o_o_discovery_manager.html", "interface_o_o_discovery_manager" ],
    [ "OODiscoveryOptions", "interface_o_o_discovery_options.html", "interface_o_o_discovery_options" ],
    [ "OODtoAsset", "interface_o_o_dto_asset.html", "interface_o_o_dto_asset" ],
    [ "OODynamicChannel", "interface_o_o_dynamic_channel.html", "interface_o_o_dynamic_channel" ],
    [ "OOEmbeddedSecureURLGenerator", "interface_o_o_embedded_secure_u_r_l_generator.html", "interface_o_o_embedded_secure_u_r_l_generator" ],
    [ "OOEmbeddedSignatureGenerator", "interface_o_o_embedded_signature_generator.html", "interface_o_o_embedded_signature_generator" ],
    [ "<OOEmbedTokenGenerator >", "protocol_o_o_embed_token_generator_01-p.html", "protocol_o_o_embed_token_generator_01-p" ],
    [ "<OOFairplayContentKeyDelegate>", "protocol_o_o_fairplay_content_key_delegate-p.html", "protocol_o_o_fairplay_content_key_delegate-p" ],
    [ "OOFCCTVRating", "interface_o_o_f_c_c_t_v_rating.html", "interface_o_o_f_c_c_t_v_rating" ],
    [ "OOFCCTVRatingConfiguration", "interface_o_o_f_c_c_t_v_rating_configuration.html", "interface_o_o_f_c_c_t_v_rating_configuration" ],
    [ "OOFCCTVRatingStampView", "interface_o_o_f_c_c_t_v_rating_stamp_view.html", "interface_o_o_f_c_c_t_v_rating_stamp_view" ],
    [ "OOFCCTVRatingVideoView", "interface_o_o_f_c_c_t_v_rating_video_view.html", "interface_o_o_f_c_c_t_v_rating_video_view" ],
    [ "OOFullscreenButton", "interface_o_o_fullscreen_button.html", null ],
    [ "OOImages", "interface_o_o_images.html", "interface_o_o_images" ],
    [ "OOIQAnalyticsPlugin", "interface_o_o_i_q_analytics_plugin.html", "interface_o_o_i_q_analytics_plugin" ],
    [ "OOIQConfiguration", "interface_o_o_i_q_configuration.html", "interface_o_o_i_q_configuration" ],
    [ "OOIQOfflineManager", "interface_o_o_i_q_offline_manager.html", "interface_o_o_i_q_offline_manager" ],
    [ "OOIQOfflineManager(Internal)", "category_o_o_i_q_offline_manager_07_internal_08.html", "category_o_o_i_q_offline_manager_07_internal_08" ],
    [ "<OOLifeCycle>", "protocol_o_o_life_cycle-p.html", "protocol_o_o_life_cycle-p" ],
    [ "OOManagedAdsPlugin", "interface_o_o_managed_ads_plugin.html", "interface_o_o_managed_ads_plugin" ],
    [ "OOManagedAdSpot", "interface_o_o_managed_ad_spot.html", "interface_o_o_managed_ad_spot" ],
    [ "OOModule", "interface_o_o_module.html", "interface_o_o_module" ],
    [ "OONextButton", "interface_o_o_next_button.html", null ],
    [ "OOOfflineVideo", "interface_o_o_offline_video.html", "interface_o_o_offline_video" ],
    [ "OOOoyalaAdSpot", "interface_o_o_ooyala_ad_spot.html", "interface_o_o_ooyala_ad_spot" ],
    [ "OOOoyalaAPIClient", "interface_o_o_ooyala_a_p_i_client.html", "interface_o_o_ooyala_a_p_i_client" ],
    [ "OOOoyalaError", "interface_o_o_ooyala_error.html", "interface_o_o_ooyala_error" ],
    [ "OOOoyalaPlayer", "interface_o_o_ooyala_player.html", "interface_o_o_ooyala_player" ],
    [ "OOOoyalaPlayer(AdPluginManagement)", "category_o_o_ooyala_player_07_ad_plugin_management_08.html", "category_o_o_ooyala_player_07_ad_plugin_management_08" ],
    [ "OOOoyalaPlayer(Ads)", "category_o_o_ooyala_player_07_ads_08.html", "category_o_o_ooyala_player_07_ads_08" ],
    [ "OOOoyalaPlayer(AppEvents)", "category_o_o_ooyala_player_07_app_events_08.html", "category_o_o_ooyala_player_07_app_events_08" ],
    [ "OOOoyalaPlayer(Cast)", "category_o_o_ooyala_player_07_cast_08.html", "category_o_o_ooyala_player_07_cast_08" ],
    [ "OOOoyalaPlayer(Channel)", "category_o_o_ooyala_player_07_channel_08.html", "category_o_o_ooyala_player_07_channel_08" ],
    [ "OOOoyalaPlayer(ClosedCaptions)", "category_o_o_ooyala_player_07_closed_captions_08.html", "category_o_o_ooyala_player_07_closed_captions_08" ],
    [ "OOOoyalaPlayer(MoviePlayerCreation)", "category_o_o_ooyala_player_07_movie_player_creation_08.html", "category_o_o_ooyala_player_07_movie_player_creation_08" ],
    [ "OOOoyalaPlayer(MultiAudio)", "category_o_o_ooyala_player_07_multi_audio_08.html", "category_o_o_ooyala_player_07_multi_audio_08" ],
    [ "OOOoyalaPlayer(Playback)", "category_o_o_ooyala_player_07_playback_08.html", "category_o_o_ooyala_player_07_playback_08" ],
    [ "OOOoyalaPlayer(PlaybackSpeed)", "category_o_o_ooyala_player_07_playback_speed_08.html", null ],
    [ "OOOoyalaPlayer(PlaybackWorkflow)", "category_o_o_ooyala_player_07_playback_workflow_08.html", "category_o_o_ooyala_player_07_playback_workflow_08" ],
    [ "OOOoyalaPlayer(UI)", "category_o_o_ooyala_player_07_u_i_08.html", "category_o_o_ooyala_player_07_u_i_08" ],
    [ "<OOOoyalaPlayerDelegate >", "protocol_o_o_ooyala_player_delegate_01-p.html", "protocol_o_o_ooyala_player_delegate_01-p" ],
    [ "OOOoyalaPlayerStateConverter", "interface_o_o_ooyala_player_state_converter.html", "interface_o_o_ooyala_player_state_converter" ],
    [ "OOOoyalaPlayerViewController", "interface_o_o_ooyala_player_view_controller.html", "interface_o_o_ooyala_player_view_controller" ],
    [ "OOOoyalaSimpleTVPlayerViewController", "interface_o_o_ooyala_simple_t_v_player_view_controller.html", "interface_o_o_ooyala_simple_t_v_player_view_controller" ],
    [ "OOOptions", "interface_o_o_options.html", "interface_o_o_options" ],
    [ "OOOrderedDictionary", "interface_o_o_ordered_dictionary.html", "interface_o_o_ordered_dictionary" ],
    [ "<OOPaginatedParentItem>", "protocol_o_o_paginated_parent_item-p.html", "protocol_o_o_paginated_parent_item-p" ],
    [ "OOPiPButton", "interface_o_o_pi_p_button.html", "interface_o_o_pi_p_button" ],
    [ "<OOPlayableItem >", "protocol_o_o_playable_item_01-p.html", "protocol_o_o_playable_item_01-p" ],
    [ "OOPlayer", "interface_o_o_player.html", "interface_o_o_player" ],
    [ "OOPlayerDomain", "interface_o_o_player_domain.html", "interface_o_o_player_domain" ],
    [ "<OOPlayerInfo >", "protocol_o_o_player_info_01-p.html", "protocol_o_o_player_info_01-p" ],
    [ "<OOPlayerProtocol>", "protocol_o_o_player_protocol-p.html", "protocol_o_o_player_protocol-p" ],
    [ "OOPlayPauseButton", "interface_o_o_play_pause_button.html", "interface_o_o_play_pause_button" ],
    [ "OOPreviousButton", "interface_o_o_previous_button.html", null ],
    [ "OOScalableImageButton", "interface_o_o_scalable_image_button.html", "interface_o_o_scalable_image_button" ],
    [ "<OOSecureURLGenerator >", "protocol_o_o_secure_u_r_l_generator_01-p.html", "protocol_o_o_secure_u_r_l_generator_01-p" ],
    [ "OOSeekInfo", "interface_o_o_seek_info.html", "interface_o_o_seek_info" ],
    [ "<OOSignatureGenerator >", "protocol_o_o_signature_generator_01-p.html", "protocol_o_o_signature_generator_01-p" ],
    [ "OOStateNotifier", "interface_o_o_state_notifier.html", "interface_o_o_state_notifier" ],
    [ "OOStream", "interface_o_o_stream.html", "interface_o_o_stream" ],
    [ "OOStreamPlayer", "interface_o_o_stream_player.html", "interface_o_o_stream_player" ],
    [ "<OOStreamPlayerMappingCreator >", "protocol_o_o_stream_player_mapping_creator_01-p.html", "protocol_o_o_stream_player_mapping_creator_01-p" ],
    [ "<OOStreamPlayerMappingPredicate >", "protocol_o_o_stream_player_mapping_predicate_01-p.html", "protocol_o_o_stream_player_mapping_predicate_01-p" ],
    [ "OOTBXML", "interface_o_o_t_b_x_m_l.html", "interface_o_o_t_b_x_m_l" ],
    [ "OOTBXML(StaticFunctions)", "category_o_o_t_b_x_m_l_07_static_functions_08.html", "category_o_o_t_b_x_m_l_07_static_functions_08" ],
    [ "OOTransparentToolbar", "interface_o_o_transparent_toolbar.html", null ],
    [ "OOUIUtils", "interface_o_o_u_i_utils.html", "interface_o_o_u_i_utils" ],
    [ "OOUnbundledVideo", "interface_o_o_unbundled_video.html", "interface_o_o_unbundled_video" ],
    [ "OOVASTAd", "interface_o_o_v_a_s_t_ad.html", "interface_o_o_v_a_s_t_ad" ],
    [ "OOVASTAdSpot", "interface_o_o_v_a_s_t_ad_spot.html", "interface_o_o_v_a_s_t_ad_spot" ],
    [ "OOVASTCompanion", "interface_o_o_v_a_s_t_companion.html", "interface_o_o_v_a_s_t_companion" ],
    [ "OOVASTCompanionAds", "interface_o_o_v_a_s_t_companion_ads.html", "interface_o_o_v_a_s_t_companion_ads" ],
    [ "OOVASTCreative", "interface_o_o_v_a_s_t_creative.html", "interface_o_o_v_a_s_t_creative" ],
    [ "OOVASTIcon", "interface_o_o_v_a_s_t_icon.html", "interface_o_o_v_a_s_t_icon" ],
    [ "OOVASTLinearAd", "interface_o_o_v_a_s_t_linear_ad.html", "interface_o_o_v_a_s_t_linear_ad" ],
    [ "OOVASTNonLinear", "interface_o_o_v_a_s_t_non_linear.html", "interface_o_o_v_a_s_t_non_linear" ],
    [ "OOVASTNonLinearAds", "interface_o_o_v_a_s_t_non_linear_ads.html", "interface_o_o_v_a_s_t_non_linear_ads" ],
    [ "OOVASTOffset", "interface_o_o_v_a_s_t_offset.html", "interface_o_o_v_a_s_t_offset" ],
    [ "OOVASTResource", "interface_o_o_v_a_s_t_resource.html", "interface_o_o_v_a_s_t_resource" ],
    [ "OOVASTStream", "interface_o_o_v_a_s_t_stream.html", "interface_o_o_v_a_s_t_stream" ],
    [ "OOVASTUtils", "interface_o_o_v_a_s_t_utils.html", "interface_o_o_v_a_s_t_utils" ],
    [ "OOVASTVMAPAdHelper", "interface_o_o_v_a_s_t_v_m_a_p_ad_helper.html", "interface_o_o_v_a_s_t_v_m_a_p_ad_helper" ],
    [ "OOVASTVMAPAdSpot", "interface_o_o_v_a_s_t_v_m_a_p_ad_spot.html", "interface_o_o_v_a_s_t_v_m_a_p_ad_spot" ],
    [ "OOVideo", "interface_o_o_video.html", "interface_o_o_video" ],
    [ "OOVideo(Internal)", "category_o_o_video_07_internal_08.html", "category_o_o_video_07_internal_08" ],
    [ "OOVideoGravityButton", "interface_o_o_video_gravity_button.html", "interface_o_o_video_gravity_button" ],
    [ "OOVolumeButton", "interface_o_o_volume_button.html", null ],
    [ "ScrubberSliderFraming", "interface_scrubber_slider_framing.html", "interface_scrubber_slider_framing" ]
];