var annotated_dup =
[
    [ "IMAAd", "interface_i_m_a_ad.html", "interface_i_m_a_ad" ],
    [ "IMAAdDisplayContainer", "interface_i_m_a_ad_display_container.html", "interface_i_m_a_ad_display_container" ],
    [ "IMAAdError", "interface_i_m_a_ad_error.html", "interface_i_m_a_ad_error" ],
    [ "IMAAdEvent", "interface_i_m_a_ad_event.html", "interface_i_m_a_ad_event" ],
    [ "IMAAdLoadingErrorData", "interface_i_m_a_ad_loading_error_data.html", "interface_i_m_a_ad_loading_error_data" ],
    [ "<IMAAdPlaybackInfo>", "protocol_i_m_a_ad_playback_info-p.html", "protocol_i_m_a_ad_playback_info-p" ],
    [ "IMAAdPodInfo", "interface_i_m_a_ad_pod_info.html", "interface_i_m_a_ad_pod_info" ],
    [ "IMAAdsLoadedData", "interface_i_m_a_ads_loaded_data.html", "interface_i_m_a_ads_loaded_data" ],
    [ "IMAAdsLoader", "interface_i_m_a_ads_loader.html", "interface_i_m_a_ads_loader" ],
    [ "<IMAAdsLoaderDelegate>", "protocol_i_m_a_ads_loader_delegate-p.html", "protocol_i_m_a_ads_loader_delegate-p" ],
    [ "IMAAdsManager", "interface_i_m_a_ads_manager.html", "interface_i_m_a_ads_manager" ],
    [ "<IMAAdsManagerDelegate>", "protocol_i_m_a_ads_manager_delegate-p.html", "protocol_i_m_a_ads_manager_delegate-p" ],
    [ "IMAAdsRenderingSettings", "interface_i_m_a_ads_rendering_settings.html", "interface_i_m_a_ads_rendering_settings" ],
    [ "IMAAdsRequest", "interface_i_m_a_ads_request.html", "interface_i_m_a_ads_request" ],
    [ "IMAAVPlayerContentPlayhead", "interface_i_m_a_a_v_player_content_playhead.html", "interface_i_m_a_a_v_player_content_playhead" ],
    [ "IMAAVPlayerVideoDisplay", "interface_i_m_a_a_v_player_video_display.html", "interface_i_m_a_a_v_player_video_display" ],
    [ "<IMAAVPlayerVideoDisplayDelegate>", "protocol_i_m_a_a_v_player_video_display_delegate-p.html", "protocol_i_m_a_a_v_player_video_display_delegate-p" ],
    [ "IMACompanionAdSlot", "interface_i_m_a_companion_ad_slot.html", "interface_i_m_a_companion_ad_slot" ],
    [ "<IMACompanionDelegate>", "protocol_i_m_a_companion_delegate-p.html", "protocol_i_m_a_companion_delegate-p" ],
    [ "<IMAContentPlayhead>", "protocol_i_m_a_content_playhead-p.html", "protocol_i_m_a_content_playhead-p" ],
    [ "IMACuepoint", "interface_i_m_a_cuepoint.html", "interface_i_m_a_cuepoint" ],
    [ "IMALiveStreamRequest", "interface_i_m_a_live_stream_request.html", "interface_i_m_a_live_stream_request" ],
    [ "IMAPictureInPictureProxy", "interface_i_m_a_picture_in_picture_proxy.html", "interface_i_m_a_picture_in_picture_proxy" ],
    [ "IMASettings", "interface_i_m_a_settings.html", "interface_i_m_a_settings" ],
    [ "IMAStreamManager", "interface_i_m_a_stream_manager.html", "interface_i_m_a_stream_manager" ],
    [ "<IMAStreamManagerDelegate>", "protocol_i_m_a_stream_manager_delegate-p.html", "protocol_i_m_a_stream_manager_delegate-p" ],
    [ "IMAStreamRequest", "interface_i_m_a_stream_request.html", "interface_i_m_a_stream_request" ],
    [ "<IMAVideoDisplay >", "protocol_i_m_a_video_display_01-p.html", "protocol_i_m_a_video_display_01-p" ],
    [ "<IMAVideoDisplayDelegate>", "protocol_i_m_a_video_display_delegate-p.html", "protocol_i_m_a_video_display_delegate-p" ],
    [ "IMAVODStreamRequest", "interface_i_m_a_v_o_d_stream_request.html", "interface_i_m_a_v_o_d_stream_request" ],
    [ "<IMAWebOpenerDelegate>", "protocol_i_m_a_web_opener_delegate-p.html", "protocol_i_m_a_web_opener_delegate-p" ],
    [ "ManagedImaAdsManager", "interface_managed_ima_ads_manager.html", "interface_managed_ima_ads_manager" ],
    [ "OOIMAAdPlayer", "interface_o_o_i_m_a_ad_player.html", "interface_o_o_i_m_a_ad_player" ],
    [ "OOIMAAdPlayMetadata", "interface_o_o_i_m_a_ad_play_metadata.html", "interface_o_o_i_m_a_ad_play_metadata" ],
    [ "<OOIMAAdsManagerDelegate>", "protocol_o_o_i_m_a_ads_manager_delegate-p.html", "protocol_o_o_i_m_a_ads_manager_delegate-p" ],
    [ "OOIMAConfiguration", "interface_o_o_i_m_a_configuration.html", "interface_o_o_i_m_a_configuration" ],
    [ "OOIMAManager", "interface_o_o_i_m_a_manager.html", "interface_o_o_i_m_a_manager" ],
    [ "<OOIMAManagerDelegate>", "protocol_o_o_i_m_a_manager_delegate-p.html", "protocol_o_o_i_m_a_manager_delegate-p" ],
    [ "OOIMAPlayheadDelegate", "interface_o_o_i_m_a_playhead_delegate.html", "interface_o_o_i_m_a_playhead_delegate" ],
    [ "OOOoyalaWeakWrapper", "interface_o_o_ooyala_weak_wrapper.html", "interface_o_o_ooyala_weak_wrapper" ]
];