{
  "openapi": "3.0.0",
  "info": {
    "title": "Brightcove CMS API Reference",
    "description": "Reference for the Brightcove CMS API, used to access and manage your media library. To test API requests, you can use our <a href=\"https://support.brightcove.com/developer-tools-and-concepts\" target=\"_blank\">API Testing Tools</a>. For permissions needed for OAuth credentials, see <a href=\"https://support.brightcove.com/api-operations-client-credentials-requests\" target=\"_blank\">API Operations</a>. For information on authenticating API requests, see <a href=\"https://s[...]",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "https://cms.api.brightcove.com/v1",
      "variables": {}
    }
  ],
  "paths": {
    "/accounts/{account_id}/counts/playlists": {
      "get": {
        "tags": [
          "Playlists"
        ],
        "summary": "Get_Playlist_Count",
        "description": "Gets a count of playlists in the account for the account ",
        "operationId": "GetPlaylistCount",
        "deprecated": false,
        "security": [
          {"BC_OAuth2": ["video-cloud/playlist/read"]}
        ],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      }
    },
    "/accounts/{account_id}/counts/playlists/{playlist_id}/videos": {
      "get": {
        "tags": [
          "Playlists"
        ],
        "summary": "Get_Video_Count_in_Playlist",
        "description": "Gets a count of the videos in a playlist for the account ",
        "operationId": "GetVideoCountInPlaylist",
        "deprecated": false,
        "security": [
          {"BC_OAuth2": ["video-cloud/playlist/read"]}
        ],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      }
    },
    "/accounts/{account_id}/counts/videos": {
      "get": {
        "tags": [
          "Videos"
        ],
        "summary": "Get_Video_Count",
        "description": "Gets count of videos for the account or a search ",
        "operationId": "GetVideoCount",
        "deprecated": false,
        "security": [
          {"BC_OAuth2": ["video-cloud/video/read"]}
        ],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      }
    },
    "/accounts/{account_id}/folders": {
      "get": {
        "tags": [
          "Folders"
        ],
        "summary": "Get_Folders",
        "description": "Gets list of folders for the account ",
        "operationId": "GetFolders",
        "deprecated": false,
        "security": [
          {"BC_OAuth2": ["video-cloud/video/read"]}
        ],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      },
      "post": {
        "tags": [
          "Folders"
        ],
        "summary": "Create_Folder",
        "description": "Create a new folder for the account ",
        "operationId": "CreateFolder",
        "deprecated": false,
        "security": [{"BC_OAuth2": ["video-cloud/video/create"]}],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      }
    },
    "/accounts/{account_id}/folders/{folder_id}": {
      "get": {
        "tags": [
          "Folders"
        ],
        "summary": "Get_FolderInformation",
        "description": "Gets information about a folder ",
        "operationId": "GetFolderinformation",
        "deprecated": false,
        "security": [{"BC_OAuth2": ["video-cloud/video/read"]}],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      },
      "delete": {
        "tags": [
          "Folders"
        ],
        "summary": "Delete_Folder",
        "description": "Delete a folder ",
        "operationId": "DeleteFolder",
        "deprecated": false,
        "security": [{"BC_OAuth2": ["video-cloud/video/delete"]}],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      },
      "patch": {
        "tags": [
          "Folders"
        ],
        "summary": "Update_Folder_Name",
        "description": "Update the folder name ",
        "operationId": "UpdateFolderName",
        "deprecated": false,
        "security": [{"BC_OAuth2": ["video-cloud/video/update"]}],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      }
    },
    "/accounts/{account_id}/folders/{folder_id}/videos": {
      "get": {
        "tags": [
          "Folders"
        ],
        "summary": "Get_Videos_in_Folder",
        "description": "Gets list of video objects in a folder ",
        "operationId": "GetVideosInFolder",
        "deprecated": false,
        "security": [{"BC_OAuth2": ["video-cloud/video/read"]}],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      }
    },
    "/accounts/{account_id}/folders/{folder_id}/videos/{video_id}": {
      "put": {
        "tags": [
          "Folders"
        ],
        "summary": "Add_Video_to_Folder",
        "description": "Add a video to a folder ",
        "operationId": "AddVideoToFolder",
        "deprecated": false,
        "security": [{"BC_OAuth2": ["video-cloud/video/update"]}],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      },
      "delete": {
        "tags": [
          "Folders"
        ],
        "summary": "Remove_Video_from_Folder",
        "description": "Remove a video from a folder ",
        "operationId": "RemoveVideoFromFolder",
        "deprecated": false,
        "security": [{"BC_OAuth2": ["video-cloud/video/update"]}],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      }
    },
    "/accounts/{account_id}/playlists": {
      "get": {
        "tags": [
          "Playlists"
        ],
        "summary": "Get_Playlists",
        "description": "Gets a page of playlist objects for the account ",
        "operationId": "GetPlaylists",
        "deprecated": false,
        "security": [{"BC_OAuth2": ["video-cloud/playlist/read"]}],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      },
      "post": {
        "tags": [
          "Playlists"
        ],
        "summary": "Create_Playlist",
        "description": "Creates a new playlist ",
        "operationId": "CreatePlaylist",
        "deprecated": false,
        "security": [{"BC_OAuth2": ["video-cloud/playlist/create"]}],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      }
    },
    "/accounts/{account_id}/playlists/{playlist_id}": {
      "get": {
        "tags": [
          "Playlists"
        ],
        "summary": "Get_Playlist_by_ID",
        "description": "Gets a playlist object for the account ",
        "operationId": "GetPlaylistById",
        "deprecated": false,
        "security": [{"BC_OAuth2": ["video-cloud/playlist/read"]}],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      },
      "delete": {
        "tags": [
          "Playlists"
        ],
        "summary": "Delete_Playlists",
        "description": "Deletes a playlist ",
        "operationId": "DeletePlaylists",
        "deprecated": false,
        "security": [{"BC_OAuth2": ["video-cloud/playlist/delete"]}],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      },
      "patch": {
        "tags": [
          "Playlists"
        ],
        "summary": "Update_Playlist",
        "description": "Updates a playlist for the account ",
        "operationId": "UpdatePlaylist",
        "deprecated": false,
        "security": [{"BC_OAuth2": ["video-cloud/playlist/update"]}],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      }
    },
    "/accounts/{account_id}/playlists/{playlist_id}/videos": {
      "get": {
        "tags": [
          "Playlists"
        ],
        "summary": "Get_Videos_in_Playlist",
        "description": "Gets the video objects for videos in a playlist for the account ",
        "operationId": "GetVideosInPlaylist",
        "deprecated": false,
        "security": [{"BC_OAuth2": ["video-cloud/playlist/read"]}],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      }
    },
    "/accounts/{account_id}/subscriptions": {
      "get": {
        "tags": [
          "Notifications"
        ],
        "summary": "Get_Subscriptions_List",
        "description": "Get a list of all notification subscriptions for the account ",
        "operationId": "GetSubscriptionsList",
        "deprecated": false,
        "security": [{"BC_OAuth2": ["video-cloud/notifications/all"]}],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      },
      "post": {
        "tags": [
          "Notifications"
        ],
        "summary": "Create_Subscription",
        "description": "Establishes up to 10 endpoints that video changes should be sent to. Any change in video metadata will trigger a video change event and a notification &mdash; changes to assets used by the video will not trigger change events.",
        "operationId": "CreateSubscription",
        "deprecated": false,
        "security": [{"BC_OAuth2": ["video-cloud/notifications/all"]}],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      }
    },
    "/accounts/{account_id}/subscriptions/{subscription_id}": {
      "get": {
        "tags": [
          "Notifications"
        ],
        "summary": "Get_Subscription",
        "description": "Get a notification subscription for the account ",
        "operationId": "GetSubscription",
        "deprecated": false,
        "security": [{"BC_OAuth2": ["video-cloud/notifications/all"]}],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      },
      "delete": {
        "tags": [
          "Notifications"
        ],
        "summary": "Delete_Subscription",
        "description": "Delete a notification subscription for the account ",
        "operationId": "DeleteSubscription",
        "deprecated": false,
        "security": [{"BC_OAuth2": ["video-cloud/notifications/all"]}],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      }
    },
    "/accounts/{account_id}/video_fields": {
      "get": {
        "tags": [
          "Videos"
        ],
        "summary": "Get_Custom_Fields",
        "description": "Gets a list of custom fields for the account ",
        "operationId": "GetCustomFields",
        "deprecated": false,
        "security": [
          {"BC_OAuth2": ["video-cloud/video/read"]}
        ],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      }
    },
    "/accounts/{account_id}/videos": {
      "get": {
        "tags": [
          "Videos"
        ],
        "summary": "Get_Videos",
        "description": "Gets a page of video objects ",
        "operationId": "GetVideos",
        "deprecated": false,
        "security": [
          {"BC_OAuth2": ["video-cloud/video/read"]}
        ],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      },
      "post": {
        "tags": [
          "Videos"
        ],
        "summary": "Create_Video",
        "description": "Create a new video object in the account. Note: this does not ingest a video file - use the Dynamic Ingest API for ingestion ",
        "operationId": "CreateVideo",
        "deprecated": false,
        "security": [
          {"BC_OAuth2": ["video-cloud/video/create"]}
        ],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      }
    },
    "/accounts/{account_id}/videos/{video_id}": {
      "get": {
        "tags": [
          "Videos"
        ],
        "summary": "Get_Video_by_ID_or_Reference_ID",
        "description": "Gets a video object ",
        "operationId": "GetVideoByIdOrReferenceId",
        "deprecated": false,
        "security": [
          {"BC_OAuth2": ["video-cloud/video/read"]}
        ],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      },
      "delete": {
        "tags": [
          "Videos"
        ],
        "summary": "Delete_Video",
        "description": "Deletes a video ",
        "operationId": "DeleteVideo",
        "deprecated": false,
        "security": [
          {"BC_OAuth2": ["video-cloud/video/delete"]}
        ],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      },
      "patch": {
        "tags": [
          "Videos"
        ],
        "summary": "Update_Video",
        "description": "Update a video&#39;s metadata note that this API does not ingest any media files - use the Dynamic Ingest API for ingestion. Also note that replacing WebVTT text tracks is a two-step operation - see Add WebVTT Captions for details.",
        "operationId": "UpdateVideo",
        "deprecated": false,
        "security": [{"BC_OAuth2": ["video-cloud/video/update"]}],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      }
    },
    "/accounts/{account_id}/videos/{video_id}/audio_tracks": {
      "get": {
        "tags": [
          "Videos"
        ],
        "summary": "Get_Video_Audio_Tracks",
        "description": "Gets the audio tracks for a video Dynamic Delivery only ",
        "operationId": "GetVideoAudioTracks",
        "deprecated": false,
        "security": [{"BC_OAuth2": ["video-cloud/video/read"]}],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      }
    },
    "/accounts/{account_id}/videos/{video_id}/audio_tracks/{audio_track_id}": {
      "get": {
        "tags": [
          "Videos"
        ],
        "summary": "Get_Video_Audio_Track",
        "description": "Gets one audio track for a video by its ID Dynamic Delivery only ",
        "operationId": "GetVideoAudioTrack",
        "deprecated": false,
        "security": [{"BC_OAuth2": ["video-cloud/video/read"]}],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      },
      "delete": {
        "tags": [
          "Videos"
        ],
        "summary": "Delete_Video_Audio_Track",
        "description": "Deletes one audio track for a video by its ID Dynamic Delivery only ",
        "operationId": "DeleteVideoAudioTrack",
        "deprecated": false,
        "security": [{"BC_OAuth2": ["video-cloud/video/update"]}],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      },
      "patch": {
        "tags": [
          "Videos"
        ],
        "summary": "Update_Video_Audio_Track",
        "description": "Updates audio track metadata for a video Dynamic Delivery only ",
        "operationId": "UpdateVideoAudioTrack",
        "deprecated": false,
        "security": [{"BC_OAuth2": ["video-cloud/video/update"]}],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      }
    },
    "/accounts/{account_id}/videos/{video_id}/digital_master": {
      "get": {
        "tags": [
          "Videos"
        ],
        "summary": "Get_Digital_Master_Info",
        "description": "Gets the stored digital master for a video, if any ",
        "operationId": "GetDigitalMasterInfo",
        "deprecated": false,
        "security": [{"BC_OAuth2": ["video-cloud/video/read"]}],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      },
      "delete": {
        "tags": [
          "Videos"
        ],
        "summary": "Delete_Digital_Master",
        "description": "Deletes the archived digital master for a video. Be sure to read Digital Master Delete API before using this operation to understand the implications.",
        "operationId": "DeleteDigitalMaster",
        "deprecated": false,
        "security": [{"BC_OAuth2": ["video-cloud/asset/delete"]}],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      }
    },
    "/accounts/{account_id}/videos/{video_id}/images": {
      "get": {
        "tags": [
          "Videos"
        ],
        "summary": "Get_Video_Images",
        "description": "Gets the images for a video ",
        "operationId": "GetVideoImages",
        "deprecated": false,
        "security": [{"BC_OAuth2": ["video-cloud/video/read"]}],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      }
    },
    "/accounts/{account_id}/videos/{video_id}/ingest_jobs": {
      "get": {
        "tags": [
          "Videos"
        ],
        "summary": "Get_Status_of_Ingest_Jobs",
        "description": "Get the status of all ingest jobs associated with a video (including the orginal ingestion, replacing and retranscoding the video). NOTE: this operation only works for videos that were ingested using Dynamic Delivery profiles.",
        "operationId": "GetStatusOfIngestJobs",
        "deprecated": false,
       "security": [{"BC_OAuth2": ["video-cloud/video/read"]}],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      }
    },
    "/accounts/{account_id}/videos/{video_id}/ingest_jobs/{job_id}": {
      "get": {
        "tags": [
          "Videos"
        ],
        "summary": "Get_Status_of_Ingest_Job",
        "description": "Get the status of an ingest job associated with a video (including the orginal ingestion, replacing and retranscoding the video) ",
        "operationId": "GetStatusOfIngestJob",
        "deprecated": false,
        "security": [{"BC_OAuth2": ["video-cloud/video/read"]}],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      }
    },
    "/accounts/{account_id}/videos/{video_id}/references": {
      "get": {
        "tags": [
          "Videos"
        ],
        "summary": "Get_Playlists_for_Video",
        "description": "Gets an array of Manual (EXPLICIT) playlists that contain a video object for the account ",
        "operationId": "GetPlaylistsForVideo",
        "deprecated": false,
        "security": [{"BC_OAuth2": ["video-cloud/video/read"]}],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      },
      "delete": {
        "tags": [
          "Videos"
        ],
        "summary": "Remove_Video_from_all_Playlists",
        "description": "Removes the video from all EXPLICIT playlists for the account ",
        "operationId": "RemoveVideoFromAllPlaylists",
        "deprecated": false,
        "security": [{"BC_OAuth2": ["video-cloud/video/delete"]}],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      }
    },
    "/accounts/{account_id}/videos/{video_id}/sources": {
      "get": {
        "tags": [
          "Videos"
        ],
        "summary": "Get_Video_Sources",
        "description": "Gets an array of sources (renditions) for a video ",
        "operationId": "GetVideoSources",
        "deprecated": false,
        "security": [{"BC_OAuth2": ["video-cloud/video/read"]}],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      }
    },
    "/accounts/{account_id}/videos/{video_id}/shares": {
      "get": {
        "tags": [
          "Media Sharing"
        ],
        "summary": "List_Shares",
        "description": "Lists the existing shares for an account - this is a Master account operation - do this before sharing to insure that you are not re-sharing to an affiliate, which would overwrite any affiliate metadata changes ",
        "operationId": "ListShares",
        "deprecated": false,
        "security": [{"BC_OAuth2": ["video-cloud/video/read"]}],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      },
      "post": {
        "tags": [
          "Media Sharing"
        ],
        "summary": "Share_Video",
        "description": "Shares a video to one or more affiliates - this is an Master account operation - if the video has already been shared to an affiliate, this operation will re-share it and overwrite any affiliate metadata changes ",
        "operationId": "ShareVideo",
        "deprecated": false,
        "security": [{"BC_OAuth2": ["video-cloud/video/create"]}],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      }
    },
    "/accounts/{account_id}/videos/{video_id}/shares/{affiliate_account_id}": {
      "get": {
        "tags": [
          "Media Sharing"
        ],
        "summary": "Get_Share",
        "description": "Lists the existing shares for an account - this is a Master account operation - do this before sharing to insure that you are not re-sharing to an affiliate, which would overwrite any affiliate metadata changes ",
        "operationId": "GetShare",
        "deprecated": false,
        "security": [{"BC_OAuth2": ["video-cloud/video/read"]}],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      },
      "delete": {
        "tags": [
          "Media Sharing"
        ],
        "summary": "Unshare_Video",
        "description": "Unshares a video with a specific affiliate - this is an Master account operation - do this before sharing to insure that you are not re-sharing to an affiliate, which would overwrite any affiliate metadata changes ",
        "operationId": "UnshareVideo",
        "deprecated": false,
        "security": [{"BC_OAuth2": ["video-cloud/video/delete"]}],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      }
    },
    "/accounts/{account_id}/channels/{channel_name}/members/{affiliate_account_id}": {
      "put": {
        "tags": [
          "Media Sharing"
        ],
        "summary": "Add_Affiliate",
        "description": "Adds an affiliate to a channel - this is a Master account operation ",
        "operationId": "AddAffiliate",
        "deprecated": false,
        "security": [
          {"BC_OAuth2": ["video-cloud/sharing-relationships/update"]}
        ],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      },
      "delete": {
        "tags": [
          "Media Sharing"
        ],
        "summary": "Remove_Affiliate",
        "description": "Removes an affiliate from a channel - this is a Master account operation ",
        "operationId": "RemoveAffiliate",
        "deprecated": false,
        "security": [{"BC_OAuth2": ["video-cloud/sharing-relationships/delete"]}],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      }
    },
    "/accounts/{account_id}/contracts/{master_account_id}/broken": {
      "patch": {
        "tags": [
          "Media Sharing"
        ],
        "summary": "Approve_Contract",
        "description": "Gets a list of available sharing contracts - this is an Affiliate account operation ",
        "operationId": "ApproveContract",
        "deprecated": false,
        "security": [{"BC_OAuth2": ["video-cloud/sharing-relationships/update"]}],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      }
    },
    "/accounts/{account_id}/channels/{channel_name}": {
      "get": {
        "tags": [
          "Media Sharing"
        ],
        "summary": "Get_Channel_Details",
        "description": "Gets settings for a sharing channel (currently there is only one default channel) - this is a Master account operation ",
        "operationId": "GetChannelDetails",
        "deprecated": false,
        "security": [{"BC_OAuth2": ["video-cloud/sharing-relationships/read"]}],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      },
      "patch": {
        "tags": [
          "Media Sharing"
        ],
        "summary": "Update_Channel",
        "description": "Updates settings for a sharing channel (currently there is only one default channel) - this is a Master account operation ",
        "operationId": "UpdateChannel",
        "deprecated": false,
        "security": [{"BC_OAuth2": ["video-cloud/sharing-relationships/update"]}],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      }
    },
    "/accounts/{account_id}/contracts/{master_account_id}": {
      "get": {
        "tags": [
          "Media Sharing"
        ],
        "summary": "Get_Contract",
        "description": "Gets a contract for a specific Master account - this is an Affiliate account operation ",
        "operationId": "GetContract",
        "deprecated": false,
        "security": [{"BC_OAuth2": ["video-cloud/sharing-relationships/read"]}],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      }
    },
    "/accounts/{account_id}/channels/{channel_name}/members": {
      "get": {
        "tags": [
          "Media Sharing"
        ],
        "summary": "List_Channel_Affiliates",
        "description": "Gets a list of affiliates for a channel - this is a Master account operation ",
        "operationId": "ListChannelAffiliates",
        "deprecated": false,
        "security": [{"BC_OAuth2": ["video-cloud/sharing-relationships/read"]}],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      }
    },
    "/accounts/{account_id}/channels": {
      "get": {
        "tags": [
          "Media Sharing"
        ],
        "summary": "List_Channels",
        "description": "Gets a list of channels (currently there is only one default channel) - this is a Master account operation ",
        "operationId": "ListChannels",
        "deprecated": false,
        "security": [{"BC_OAuth2": ["video-cloud/sharing-relationships/read"]}],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      }
    },
    "/accounts/{account_id}/contracts": {
      "get": {
        "tags": [
          "Media Sharing"
        ],
        "summary": "List_Contracts",
        "description": "Gets a list of available sharing contracts - this is an Affiliate account operation ",
        "operationId": "ListContracts",
        "deprecated": false,
        "security": [{"BC_OAuth2": ["video-cloud/sharing-relationships/read"]}],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      }
    },
    "/accounts/{account_id}/videos/{video_id}/assets": {
      "get": {
        "tags": [
          "Media Assets"
        ],
        "summary": "Get_Assets",
        "description": "Gets assets for a given video. Note: you can use /videos/ref:reference_id instead of /videos/video_id ",
        "operationId": "GetAssets",
        "deprecated": false,
        "security": [{"BC_OAuth2": ["video-cloud/video/read"]}],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      }
    },
    "/accounts/{account_id}/videos/{video_id}/assets/dynamic_renditions": {
      "get": {
        "tags": [
          "Media Assets"
        ],
        "summary": "Get_Dynamic_Renditions",
        "description": "Gets a list of dynamic renditions for a Dynamic Delivery video. Note: you can use /videos/ref:reference_id instead of /videos/video_id ",
        "operationId": "GetDynamicRenditions",
        "deprecated": false,
        "security": [{"BC_OAuth2": ["video-cloud/video/read"]}],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      }
    },
    "/accounts/{account_id}/videos/{video_id}/assets/caption": {
      "get": {
        "tags": [
          "Media Assets"
        ],
        "summary": "Get_Caption_List",
        "description": "Gets the caption file for a given video (DFXP captions for the Smart Player). Note: 1) the caption endpoint is ONLY for working with DFXP captions used in the legacy Smart Player - WebVTT captions (text_tracks) for the new Brightcove Player are managed using the Update Video operation; 2) you can use /videos/ref:reference_id instead of /videos/video_id ",
        "operationId": "GetCaptionList",
        "deprecated": false,
        "security": [{"BC_OAuth2": ["video-cloud/video/read"]}],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      },
      "post": {
        "tags": [
          "Media Assets"
        ],
        "summary": "Add_Caption",
        "description": "Adds a caption file for a remote asset (DFXP captions for the Smart Player). Note: 1) the caption endpoint is ONLY for working with DFXP captions used in the legacy Smart Player - WebVTT captions (text_tracks) for the new Brightcove Player are managed using the Update Video operation; 2) you can use /videos/ref:reference_id instead of /videos/video_id ",
        "operationId": "AddCaption",
        "deprecated": false,
        "security": [{"BC_OAuth2": ["video-cloud/video/update"]}],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      }
    },
    "/accounts/{account_id}/videos/{video_id}/assets/dash_manifests": {
      "get": {
        "tags": [
          "Media Assets"
        ],
        "summary": "Get_DASH_Manifest_List",
        "description": "Gets the dash_manifests for a given video. Notes: 1. you can have multiple dash manifests with profiles; you can have only one dash manifest without a profile, but one manifest without a profile can be combined with muliple manifests with profiles; 2. all manifests intended to be used with the CMS API should include a profile - only DASH manifests with profiles will be returned by the CMS API &mdash; only a single DASH manifest without a profile will be returned by the Me[...]",
        "operationId": "GetDashManifestList",
        "deprecated": false,
        "security": [
          {"BC_OAuth2": ["video-cloud/video/read"]}
        ],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      },
      "post": {
        "tags": [
          "Media Assets"
        ],
        "summary": "Add_DASH_Manifest",
        "description": "Adds a location for a remote DASH manifest Notes: 1. you can have multiple dash manifests with profiles; you can have only one dash manifest without a profile, but one manifest without a profile can be combined with muliple manifests with profiles; 2. all manifests intended to be used with the CMS API should include a profile - only DASH manifests with profiles will be returned by the CMS API &mdash; only a single DASH manifest without a profile will be returned by the Me[...]",
        "operationId": "AddDashManifest",
        "deprecated": false,
        "security": [
          {"BC_OAuth2": ["video-cloud/video/update"]}
        ],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      }
    },
    "/accounts/{account_id}/videos/{video_id}/assets/hds_manifest": {
      "get": {
        "tags": [
          "Media Assets"
        ],
        "summary": "Get_HDS_Manifest_List",
        "description": "Gets the hds_manifest file for a given video. Note: you can use /videos/ref:reference_id instead of /videos/video_id ",
        "operationId": "GetHdsManifestList",
        "deprecated": false,
        "security": [
          {"BC_OAuth2": ["video-cloud/video/read"]}
        ],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      },
      "post": {
        "tags": [
          "Media Assets"
        ],
        "summary": "Add_HDS_Manifest",
        "description": "Adds the location of an hds_manifest file for a remote asset. Note: you can use /videos/ref:reference_id instead of /videos/video_id ",
        "operationId": "AddHdsManifest",
        "deprecated": false,
        "security": [
          {"BC_OAuth2": ["video-cloud/video/update"]}
        ],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      }
    },
    "/accounts/{account_id}/videos/{video_id}/assets/hls_manifest": {
      "get": {
        "tags": [
          "Media Assets"
        ],
        "summary": "Get_HLS_Manifest_List",
        "description": "Gets the hls_manifest for a given video. Notes: 1) you can use /videos/ref:reference_id instead of /videos/video_id 2) this method only returns a remote asset HTL manifest, not manifests for ingested videos ",
        "operationId": "GetHlsManifestList",
        "deprecated": false,
        "security": [
          {"BC_OAuth2": ["video-cloud/video/read"]}
        ],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      },
      "post": {
        "tags": [
          "Media Assets"
        ],
        "summary": "Add_HLS_Manifest",
        "description": "Adds the location of an hls_manifest file for a remote asset. Note: you can use /videos/ref:reference_id instead of /videos/video_id ",
        "operationId": "AddHlsManifest",
        "deprecated": false,
        "security": [
          {"BC_OAuth2": ["video-cloud/video/update"]}
        ],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      }
    },
    "/accounts/{account_id}/videos/{video_id}/assets/ismc_manifest": {
      "get": {
        "tags": [
          "Media Assets"
        ],
        "summary": "Get_ISMC_Manifest_List",
        "description": "Gets the ismc_manifest files for a given video. Note: you can use /videos/ref:reference_id instead of /videos/video_id ",
        "operationId": "GetIsmcManifestList",
        "deprecated": false,
        "security": [
          {"BC_OAuth2": ["video-cloud/video/read"]}
        ],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      },
      "post": {
        "tags": [
          "Media Assets"
        ],
        "summary": "Add_ISMC_Manifest",
        "description": "Adds the location of an ismc_manifest file for a remote asset. Note: you can use /videos/ref:reference_id instead of /videos/video_id ",
        "operationId": "AddIsmcManifest",
        "deprecated": false,
        "security": [
          {"BC_OAuth2": ["video-cloud/video/update"]}
        ],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      }
    },
    "/accounts/{account_id}/videos/{video_id}/assets/ism_manifest": {
      "get": {
        "tags": [
          "Media Assets"
        ],
        "summary": "Get_ISM_Manifest_List",
        "description": "Gets the ism_manifest for a given video. Note: you can use /videos/ref:reference_id instead of /videos/video_id ",
        "operationId": "GetIsmManifestList",
        "deprecated": false,
        "security": [
          {"BC_OAuth2": ["video-cloud/video/read"]}
        ],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      },
      "post": {
        "tags": [
          "Media Assets"
        ],
        "summary": "Add_ISM_Manifest",
        "description": "Adds the location of an ism_manifest file for a remote asset. Note: you can use /videos/ref:reference_id instead of /videos/video_id ",
        "operationId": "AddIsmManifest",
        "deprecated": false,
        "security": [
          {"BC_OAuth2": ["video-cloud/video/update"]}
        ],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      }
    },
    "/accounts/{account_id}/videos/{video_id}/assets/poster": {
      "get": {
        "tags": [
          "Media Assets"
        ],
        "summary": "Get_Poster_List",
        "description": "Gets the poster file for a given video. Note that you can only add one poster for a video. Note: you can use /videos/ref:reference_id instead of /videos/video_id ",
        "operationId": "GetPosterList",
        "deprecated": false,
        "security": [
          {"BC_OAuth2": ["video-cloud/video/read"]}
        ],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      },
      "post": {
        "tags": [
          "Media Assets"
        ],
        "summary": "Add_Poster",
        "description": "Adds a poster file for a remote asset. Ingested assets must be added via the Dynamic Ingest API. Note: you can use /videos/ref:reference_id instead of /videos/video_id ",
        "operationId": "AddPoster",
        "deprecated": false,
        "security": [
          {"BC_OAuth2": ["video-cloud/video/update"]}
        ],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      }
    },
    "/accounts/{account_id}/videos/{video_id}/assets/renditions": {
      "get": {
        "tags": [
          "Media Assets"
        ],
        "summary": "Get_Rendition_List",
        "description": "Gets a list of renditions for a given video. Notes: 1) this endpoint is for renditions created using the legacy ingest profiles - for Dynamic Deliver renditions, use the `/accounts/{account_id}/videos/{video_id}/assets/dynamic_renditions` endpoint; 2) you can use /videos/ref:reference_id instead of /videos/video_id ",
        "operationId": "GetRenditionList",
        "deprecated": false,
        "security": [
          {"BC_OAuth2": ["video-cloud/video/read"]}
        ],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      },
      "post": {
        "tags": [
          "Media Assets"
        ],
        "summary": "Add_Rendition",
        "description": "Add a remote rendition to the given video. Note: you can use /videos/ref:reference_id instead of /videos/video_id ",
        "operationId": "AddRendition",
        "deprecated": false,
        "security": [
          {"BC_OAuth2": ["video-cloud/video/update"]}
        ],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      }
    },
    "/accounts/{account_id}/videos/{video_id}/assets/thumbnail": {
      "get": {
        "tags": [
          "Media Assets"
        ],
        "summary": "Get_Thumbnail_List",
        "description": "Gets the thumbnail for a given video. Note that you can only add one thumbnail for a video. Note: you can use /videos/ref:reference_id instead of /videos/video_id ",
        "operationId": "GetThumbnailList",
        "deprecated": false,
        "security": [
          {"BC_OAuth2": ["video-cloud/video/read"]}
        ],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      },
      "post": {
        "tags": [
          "Media Assets"
        ],
        "summary": "Add_Thumbnail",
        "description": "Adds a thumbnail file for a remote asset. Ingested assets must be added via the Dynamic Ingest API. Note: you can use /videos/ref:reference_id instead of /videos/video_id ",
        "operationId": "AddThumbnail",
        "deprecated": false,
        "security": [
          {"BC_OAuth2": ["video-cloud/video/update"]}
        ],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      }
    },
    "/accounts/{account_id}/videos/{video_id}/assets/caption/{asset_id}": {
      "get": {
        "tags": [
          "Media Assets"
        ],
        "summary": "Get_Caption",
        "description": "Gets a caption file for a given video (DFXP captions for the Smart Player). Note: 1) the caption endpoint is ONLY for working with DFXP captions used in the legacy Smart Player - WebVTT captions (text_tracks) for the new Brightcove Player are managed using the Update Video operation; 2) you can use /videos/ref:reference_id instead of /videos/video_id ",
        "operationId": "GetCaption",
        "deprecated": false,
        "security": [
          {"BC_OAuth2": ["video-cloud/video/read"]}
        ],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      },
      "delete": {
        "tags": [
          "Media Assets"
        ],
        "summary": "Delete_Caption",
        "description": "Deletes a caption file for a remote asset (DFXP captions for the Smart Player). Note: 1) the caption endpoint is ONLY for working with DFXP captions used in the legacy Smart Player - WebVTT captions (text_tracks) for the new Brightcove Player are managed using the Update Video operation; 2) you can use /videos/ref:reference_id instead of /videos/video_id ",
        "operationId": "DeleteCaption",
        "deprecated": false,
        "security": [
          {"BC_OAuth2": ["video-cloud/video/update"]}
        ],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      },
      "patch": {
        "tags": [
          "Media Assets"
        ],
        "summary": "Update_Caption",
        "description": "Updates the location of a remote caption file for a remote asset (DFXP captions for the Smart Player). Note: 1) the caption endpoint is ONLY for working with DFXP captions used in the legacy Smart Player - WebVTT captions (text_tracks) for the new Brightcove Player are managed using the Update Video operation; 2) you can use /videos/ref:reference_id instead of /videos/video_id ",
        "operationId": "UpdateCaption",
        "deprecated": false,
        "security": [
          {"BC_OAuth2": ["video-cloud/video/update"]}
        ],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      }
    },
    "/accounts/{account_id}/videos/{video_id}/assets/dash_manifests/{asset_id}": {
      "get": {
        "tags": [
          "Media Assets"
        ],
        "summary": "Get_DASH_Manifest",
        "description": "Gets a dash_manifest for a given video. Note: you can use /videos/ref:reference_id instead of /videos/video_id ",
        "operationId": "GetDashManifest",
        "deprecated": false,
        "security": [
          {"BC_OAuth2": ["video-cloud/video/read"]}
        ],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      },
      "delete": {
        "tags": [
          "Media Assets"
        ],
        "summary": "Delete_DASH_Manifest",
        "description": "Deletes an dash_manifest file for a remote asset. Note: you can use /videos/ref:reference_id instead of /videos/video_id ",
        "operationId": "DeleteDashManifest",
        "deprecated": false,
        "security": [
          {"BC_OAuth2": ["video-cloud/video/update"]}
        ],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      },
      "patch": {
        "tags": [
          "Media Assets"
        ],
        "summary": "Update_DASH_Manifest",
        "description": "Updates the location of a remote dash_manifest file for a remote asset. Note: you can use /videos/ref:reference_id instead of /videos/video_id ",
        "operationId": "UpdateDashManifest",
        "deprecated": false,
        "security": [
          {"BC_OAuth2": ["video-cloud/video/update"]}
        ],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      }
    },
    "/accounts/{account_id}/videos/{video_id}/assets/hds_manifest/{asset_id}": {
      "get": {
        "tags": [
          "Media Assets"
        ],
        "summary": "Get_HDS_Manifest",
        "description": "Gets the hds_manifest file for a given video. Note: you can use /videos/ref:reference_id instead of /videos/video_id ",
        "operationId": "GetHdsManifest",
        "deprecated": false,
        "security": [
          {"BC_OAuth2": ["video-cloud/video/read"]}
        ],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      },
      "delete": {
        "tags": [
          "Media Assets"
        ],
        "summary": "Delete_HDS_Manifest",
        "description": "Deletes an hds_manifest file for a remote asset. Note: you can use /videos/ref:reference_id instead of /videos/video_id ",
        "operationId": "DeleteHdsManifest",
        "deprecated": false,
        "security": [
          {"BC_OAuth2": ["video-cloud/video/update"]}
        ],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      },
      "patch": {
        "tags": [
          "Media Assets"
        ],
        "summary": "Update_HDS_Manifest",
        "description": "Updates the location of a remote hds_manifest file for a remote asset. Note: you can use /videos/ref:reference_id instead of /videos/video_id ",
        "operationId": "UpdateHdsManifest",
        "deprecated": false,
        "security": [
          {"BC_OAuth2": ["video-cloud/video/update"]}
        ],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      }
    },
    "/accounts/{account_id}/videos/{video_id}/assets/hls_manifest/{asset_id}": {
      "get": {
        "tags": [
          "Media Assets"
        ],
        "summary": "Get_HLS_Manifest",
        "description": "Gets an hls_manifest for a given video. Note: you can use /videos/ref:reference_id instead of /videos/video_id ",
        "operationId": "GetHlsManifest",
        "deprecated": false,
        "security": [
          {"BC_OAuth2": ["video-cloud/video/read"]}
        ],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      },
      "delete": {
        "tags": [
          "Media Assets"
        ],
        "summary": "Delete_HLS_Manifest",
        "description": "Deletes an hls_manifest file for a remote asset. Note: you can use /videos/ref:reference_id instead of /videos/video_id ",
        "operationId": "DeleteHlsManifest",
        "deprecated": false,
        "security": [
          {"BC_OAuth2": ["video-cloud/video/update"]}
        ],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      },
      "patch": {
        "tags": [
          "Media Assets"
        ],
        "summary": "Update_HLS_Manifest",
        "description": "Updates the location of a remote hls_manifest file for a remote asset. Note: you can use /videos/ref:reference_id instead of /videos/video_id ",
        "operationId": "UpdateHlsManifest",
        "deprecated": false,
        "security": [
          {"BC_OAuth2": ["video-cloud/video/update"]}
        ],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      }
    },
    "/accounts/{account_id}/videos/{video_id}/assets/ismc_manifest/{asset_id}": {
      "get": {
        "tags": [
          "Media Assets"
        ],
        "summary": "Get_ISMC_Manifest",
        "description": "Gets the ismc_manifest file for a given video. Note: you can use /videos/ref:reference_id instead of /videos/video_id ",
        "operationId": "GetIsmcManifest",
        "deprecated": false,
        "security": [
          {"BC_OAuth2": ["video-cloud/video/read"]}
        ],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      },
      "delete": {
        "tags": [
          "Media Assets"
        ],
        "summary": "Delete_ISMC_Manifest",
        "description": "Deletes an ismc_manifest file for a remote asset. Note: you can use /videos/ref:reference_id instead of /videos/video_id ",
        "operationId": "DeleteIsmcManifest",
        "deprecated": false,
        "security": [
          {"BC_OAuth2": ["video-cloud/video/update"]}
        ],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      },
      "patch": {
        "tags": [
          "Media Assets"
        ],
        "summary": "Update_ISMC_Manifest",
        "description": "Updates the location of a remote ismc_manifest file for a remote asset. Note: you can use /videos/ref:reference_id instead of /videos/video_id ",
        "operationId": "UpdateIsmcManifest",
        "deprecated": false,
        "security": [
          {"BC_OAuth2": ["video-cloud/video/update"]}
        ],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      }
    },
    "/accounts/{account_id}/videos/{video_id}/assets/ism_manifest/{asset_id}": {
      "get": {
        "tags": [
          "Media Assets"
        ],
        "summary": "Get_ISM_Manifest",
        "description": "Gets an ism_manifest for a given video. Note: you can use /videos/ref:reference_id instead of /videos/video_id ",
        "operationId": "GetIsmManifest",
        "deprecated": false,
        "security": [
          {"BC_OAuth2": ["video-cloud/video/read"]}
        ],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      },
      "delete": {
        "tags": [
          "Media Assets"
        ],
        "summary": "Delete_ISM_Manifest",
        "description": "Deletes an ism_manifest file for a remote asset. Note: you can use /videos/ref:reference_id instead of /videos/video_id ",
        "operationId": "DeleteIsmManifest",
        "deprecated": false,
        "security": [
          {"BC_OAuth2": ["video-cloud/video/update"]}
        ],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      },
      "patch": {
        "tags": [
          "Media Assets"
        ],
        "summary": "Update_ISM_Manifest",
        "description": "Updates the location of a remote ism_manifest file for a remote asset. Note: you can use /videos/ref:reference_id instead of /videos/video_id ",
        "operationId": "UpdateIsmManifest",
        "deprecated": false,
        "security": [
          {"BC_OAuth2": ["video-cloud/video/update"]}
        ],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      }
    },
    "/accounts/{account_id}/videos/{video_id}/assets/poster/{asset_id}": {
      "get": {
        "tags": [
          "Media Assets"
        ],
        "summary": "Get_Poster",
        "description": "Gets a poster file for a given video. Note that you can only add one poster for a video. Note: you can use /videos/ref:reference_id instead of /videos/video_id ",
        "operationId": "GetPoster",
        "deprecated": false,
        "security": [
          {"BC_OAuth2": ["video-cloud/video/read"]}
        ],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      },
      "delete": {
        "tags": [
          "Media Assets"
        ],
        "summary": "Delete_Poster",
        "description": "Deletes a poster file for a remote asset. Note that you can only add one poster for a video. Note: you can use /videos/ref:reference_id instead of /videos/video_id ",
        "operationId": "DeletePoster",
        "deprecated": false,
        "security": [
          {"BC_OAuth2": ["video-cloud/video/update"]}
        ],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      },
      "patch": {
        "tags": [
          "Media Assets"
        ],
        "summary": "Update_Poster",
        "description": "Updates the location of a remote poster file for a remote asset. Note: you can use /videos/ref:reference_id instead of /videos/video_id ",
        "operationId": "UpdatePoster",
        "deprecated": false,
        "security": [
          {"BC_OAuth2": ["video-cloud/video/update"]}
        ],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      }
    },
    "/accounts/{account_id}/videos/{video_id}/assets/renditions/{asset_id}": {
      "get": {
        "tags": [
          "Media Assets"
        ],
        "summary": "Get_Rendition",
        "description": "Gets a specified rendition for a video. Note: you can use /videos/ref:reference_id instead of /videos/video_id ",
        "operationId": "GetRendition",
        "deprecated": false,
        "security": [
          {"BC_OAuth2": ["video-cloud/video/read"]}
        ],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      },
      "delete": {
        "tags": [
          "Media Assets"
        ],
        "summary": "Delete_Rendition",
        "description": "Deletes a rendition for the given video. Note: this operation is only for remote renditions for remote asset videos &mdash; do not use it for renditions created by Video Cloud for ingested videos ",
        "operationId": "DeleteRendition",
        "deprecated": false,
        "security": [
          {"BC_OAuth2": ["video-cloud/video/update"]}
        ],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      },
      "patch": {
        "tags": [
          "Media Assets"
        ],
        "summary": "Update_Rendition",
        "description": "Update the location for a remote rendition. Note: you can use /videos/ref:reference_id instead of /videos/video_id ",
        "operationId": "UpdateRendition",
        "deprecated": false,
        "security": [
          {"BC_OAuth2": ["video-cloud/video/update"]}
        ],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      }
    },
    "/accounts/{account_id}/videos/{video_id}/assets/thumbnail/{asset_id}": {
      "get": {
        "tags": [
          "Media Assets"
        ],
        "summary": "Get_Thumbnail",
        "description": "Gets a thumbnail file for a given video. Note that you can only add one thumbnail for a video. Note: you can use /videos/ref:reference_id instead of /videos/video_id ",
        "operationId": "GetThumbnail",
        "deprecated": false,
        "security": [
          {"BC_OAuth2": ["video-cloud/video/read"]}
        ],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      },
      "delete": {
        "tags": [
          "Media Assets"
        ],
        "summary": "Delete_Thumbnail",
        "description": "Deletes a thumbnail file for a remote asset. Note that you can only add one thumbnail for a video. Note: you can use /videos/ref:reference_id instead of /videos/video_id ",
        "operationId": "DeleteThumbnail",
        "deprecated": false,
        "security": [
          {"BC_OAuth2": ["video-cloud/video/read"]}
        ],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      },
      "patch": {
        "tags": [
          "Media Assets"
        ],
        "summary": "Update_Thumbnail",
        "description": "Updates the location of a remote thumbnail file for a remote asset. Note: you can use /videos/ref:reference_id instead of /videos/video_id ",
        "operationId": "UpdateThumbnail",
        "deprecated": false,
        "security": [
          {"BC_OAuth2": ["video-cloud/video/read"]}
        ],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      }
    }
  },
  "components": {
  }
}
