openapi: 3.0.0
info:
  title: Brightcove CMS API Reference
  description: >-
    Reference for the Brightcove CMS API, used to access and manage your media library. To test API requests, you can use our [API Testing Tools](https://support.brightcove.com/developer-tools-and-concepts). For permissions needed for OAuth credentials, see [API Operations](https://support.brightcove.com/api-operations-client-credentials-requests). For information on authenticating API requests, see the [OAuth Overview](https://support.brightcove.com/overview-oauth-api-v4).

     **Base URL**: https://cms.api.brightcove.com/v1
  version: 1.0.0
servers:
  - url: 'https://cms.api.brightcove.com/v1'
    variables: {}
tags:
  - name: Videos
    description: 'Operations for managing videos, video metadata, audio tracks, and more.'
  - name: Media Sharing
    description: >-
      Operations for setting up sharing relationships and sharing videos between
      different Video Cloud accounts.
  - name: Playlists
    description: Operations for managing video playlists.
  - name: Folders
    description: Operations for managing folders to organize your videos.
  - name: Notifications
    description: >-
      Operations for setting up and managing notifications of changes to your
      video library.
  - name: Media Assets
    description: >-
      Operations for managing renditions, manifests, and other media assets.
      These operations are used mainly for remote assets.
  - name: Legacy
    description: >-
      Legacy operations - unless your account is still using the legacy ingest
      system instead of Dynamic Delivery, these operations are not relevant.
paths:
  '/accounts/{account_id}/videos':
    get:
      tags:
        - Videos
      summary: Get Videos
      description: 'Gets a page of video objects '
      operationId: GetVideos
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/video/read
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
    post:
      tags:
        - Videos
      summary: Create Video
      description: >-
        Create a new video object in the account. Note: this does not ingest a
        video file - use the Dynamic Ingest API for ingestion
      operationId: CreateVideo
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/video/create
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  '/accounts/{account_id}/counts/videos':
    get:
      tags:
        - Videos
      summary: Get Video Count
      description: 'Gets count of videos for the account or a search '
      operationId: GetVideoCount
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/video/read
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  '/accounts/{account_id}/videos/{video_id}':
    get:
      tags:
        - Videos
      summary: 'Get Videos by ID/Reference ID'
      description: >-
        Gets a video object - you can include **up to 10** video ids seperated by commas
      operationId: GetVideoByIdOrReferenceId
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/video/read
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
    delete:
      tags:
        - Videos
      summary: Delete Video
      description: 'Deletes a video '
      operationId: DeleteVideo
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/video/delete
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
    patch:
      tags:
        - Videos
      summary: Update Video
      description: >-
        Update video metadata - note that this API does not ingest any
        media files - use the Dynamic Ingest API for ingestion. Also note that replacing WebVTT text tracks is a two-step operation - see Add WebVTT Captions for details.
      operationId: UpdateVideo
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/video/update
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  '/accounts/{account_id}/videos/{video_id}/sources':
    get:
      tags:
        - Videos
      summary: Get Video Sources
      description: 'Gets an array of sources (renditions) for a video'
      operationId: GetVideoSources
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/video/read
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  '/accounts/{account_id}/videos/{video_id}/images':
    get:
      tags:
        - Videos
      summary: Get Video Images
      description: 'Gets the images for a video '
      operationId: GetVideoImages
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/video/read
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  '/accounts/{account_id}/videos/{video_id}/audio_tracks':
    get:
      tags:
        - Videos
      summary: Get Video Audio Tracks
      description: 'Gets the audio tracks for a video Dynamic Delivery only '
      operationId: GetVideoAudioTracks
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/video/read
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  '/accounts/{account_id}/videos/{video_id}/audio_tracks/{audio_track_id}':
    get:
      tags:
        - Videos
      summary: Get Video Audio Track
      description: 'Gets one audio track for a video by its ID Dynamic Delivery only '
      operationId: GetVideoAudioTrack
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/video/read
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
    patch:
      tags:
        - Videos
      summary: Update Video Audio Track
      description: 'Updates audio track metadata for a video Dynamic Delivery only '
      operationId: UpdateVideoAudioTrack
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/video/update
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
    delete:
      tags:
        - Videos
      summary: Delete Video Audio Track
      description: 'Deletes one audio track for a video by its ID Dynamic Delivery only '
      operationId: DeleteVideoAudioTrack
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/video/update
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  '/accounts/{account_id}/videos/{video_id}/digital_master':
    get:
      tags:
        - Videos
      summary: Get Digital Master Info
      description: 'Gets the stored digital master for a video, if any '
      operationId: GetDigitalMasterInfo
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/video/read
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
    delete:
      tags:
        - Videos
      summary: Delete Digital Master
      description: >-
        Deletes the archived digital master for a video. Be sure to read Digital Master Delete API before using this operation to understand the implications.
      operationId: DeleteDigitalMaster
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/asset/delete
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  '/accounts/{account_id}/videos/{video_id}/references':
    get:
      tags:
        - Videos
      summary: Get Playlists for Video
      description: >-
        Gets an array of Manual (EXPLICIT) playlists that contain a video object for the account
      operationId: GetPlaylistsForVideo
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/video/read
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
    delete:
      tags:
        - Videos
      summary: Remove Video from all Playlists
      description: 'Removes the video from all EXPLICIT playlists for the account '
      operationId: RemoveVideoFromAllPlaylists
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/video/delete
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  '/accounts/{account_id}/videos/{video_id}/ingest_jobs':
    get:
      tags:
        - Videos
      summary: Get Status of Ingest Jobs
      description: >-
        Get the status of all ingest jobs associated with a video (including the original ingestion, replacing and retranscoding the video). NOTE: this operation only works for videos that were ingested using **Dynamic Delivery** profiles.
      operationId: GetStatusOfIngestJobs
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/video/read
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  '/accounts/{account_id}/videos/{video_id}/ingest_jobs/{job_id}':
    get:
      tags:
        - Videos
      summary: Get Status of Ingest Job
      description: >-
        Get the status of an ingest job associated with a video (including the original ingestion, replacing and retranscoding the video). NOTE: this operation only works for videos that were ingested using **Dynamic Delivery** profiles.
      operationId: GetStatusOfIngestJob
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/video/read
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  '/accounts/{account_id}/video_fields':
    get:
      tags:
        - Videos
      summary: Get Custom Fields
      description: 'Gets a list of custom fields for the account '
      operationId: GetCustomFields
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/video/read
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  '/accounts/{account_id}/channels':
    get:
      tags:
        - Media Sharing
      summary: List Channels
      description: >-
        Gets a list of channels (currently there is only one default channel) - this is a Master account operation
      operationId: ListChannels
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/sharing-relationships/read
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  '/accounts/{account_id}/channels/{channel_name}':
    get:
      tags:
        - Media Sharing
      summary: Get Channel Details
      description: >-
        Gets settings for a sharing channel (currently there is only one default channel) - this is a Master account operation
      operationId: GetChannelDetails
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/sharing-relationships/read
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
    patch:
      tags:
        - Media Sharing
      summary: Update Channel
      description: >-
        Updates settings for a sharing channel (currently there is only one default channel) - this is a Master account operation
      operationId: UpdateChannel
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/sharing-relationships/update
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  '/accounts/{account_id}/channels/{channel_name}/members':
    get:
      tags:
        - Media Sharing
      summary: List Channel Affiliates
      description: >-
        Gets a list of affiliates for a channel - this is a Master account
        operation
      operationId: ListChannelAffiliates
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/sharing-relationships/read
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  '/accounts/{account_id}/channels/{channel_name}/members/{affiliate_account_id}':
    put:
      tags:
        - Media Sharing
      summary: Add Affiliate
      description: 'Adds an affiliate to a channel - this is a Master account operation '
      operationId: AddAffiliate
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/sharing-relationships/update
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
    delete:
      tags:
        - Media Sharing
      summary: Remove Affiliate
      description: >-
        Removes an affiliate from a channel - this is a Master account operation
      operationId: RemoveAffiliate
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/sharing-relationships/delete
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  '/accounts/{account_id}/contracts/':
    get:
      tags:
        - Media Sharing
      summary: Approve Contract
      description: >-
        Gets a list of available sharing contracts - this is an Affiliate account operation
      operationId: ApproveContract
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/sharing-relationships/update
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  '/accounts/{account_id}/contracts/{master_account_id}':
    get:
      tags:
        - Media Sharing
      summary: Approve Contract
      description: >-
        Gets a list of available sharing contracts - this is an Affiliate account operation
      operationId: ApproveContract
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/sharing-relationships/update
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
    patch:
      tags:
        - Media Sharing
      summary: Approve Contract
      description: 'Approve a contract - this is an Affiliate account operation '
      operationId: ApproveContract
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/sharing-relationships/update
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  '/accounts/{account_id}/videos/{video_id}/shares':
    get:
      tags:
        - Media Sharing
      summary: List Shares
      description: >-
        Lists the existing shares for an account - this is a Master account operation - do this before sharing to insure that you are not re-sharing to an affiliate, which would overwrite any affiliate metadata changes
      operationId: ListShares
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/video/read
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
    post:
      tags:
        - Media Sharing
      summary: Share Video
      description: >-
        Shares a video to one or more affiliates - this is an Master account operation - if the video has already been shared to an affiliate, this operation will re-share it and overwrite any affiliate metadata changes
      operationId: ShareVideo
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/video/create
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  '/accounts/{account_id}/videos/{video_id}/shares/{affiliate_account_id}':
    get:
      tags:
        - Media Sharing
      summary: Get Share
      description: >-
        Lists the existing shares for an account - this is a Master account operation - do this before sharing to insure that you are not re-sharing to an affiliate, which would overwrite any affiliate metadata changes
      operationId: GetShare
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/video/read
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
    delete:
      tags:
        - Media Sharing
      summary: Unshare Video
      description: >-
        Unshares a video with a specific affiliate - this is an Master account operation - do this before sharing to insure that you are not re-sharing to an affiliate, which would overwrite any affiliate metadata changes
      operationId: UnshareVideo
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/video/delete
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  '/accounts/{account_id}/playlists':
    get:
      tags:
        - Playlists
      summary: Get Playlists
      description: 'Gets a page of playlist objects for the account '
      operationId: GetPlaylists
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/playlist/read
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
    post:
      tags:
        - Playlists
      summary: Create Playlist
      description: 'Creates a new playlist '
      operationId: CreatePlaylist
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/playlist/create
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  '/accounts/{account_id}/counts/playlists':
    get:
      tags:
        - Playlists
      summary: Get Playlist Count
      description: 'Gets a count of playlists in the account for the account '
      operationId: GetPlaylistCount
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/playlist/read
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  '/accounts/{account_id}/playlists/{playlist_id}':
    get:
      tags:
        - Playlists
      summary: Get Playlists by ID
      description: 'Gets one or more playlist objects for the account '
      operationId: GetPlaylistById
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/playlist/read
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
    patch:
      tags:
        - Playlists
      summary: Update Playlist
      description: 'Updates a playlist for the account '
      operationId: UpdatePlaylist
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/playlist/update
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
    delete:
      tags:
        - Playlists
      summary: Delete Playlist
      description: 'Deletes a playlist '
      operationId: DeletePlaylists
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/playlist/delete
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  '/accounts/{account_id}/playlists/{playlist_id}/videos':
    get:
      tags:
        - Playlists
      summary: Get Videos in Playlist
      description: 'Gets the video objects for videos in a playlist for the account '
      operationId: GetVideosInPlaylist
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/playlist/read
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  '/accounts/{account_id}/counts/playlists/{playlist_id}/videos':
    get:
      tags:
        - Playlists
      summary: Get Video Count in Playlist
      description: 'Gets a count of the videos in a playlist for the account '
      operationId: GetVideoCountInPlaylist
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/playlist/read
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  '/accounts/{account_id}/folders':
    get:
      tags:
        - Folders
      summary: Get Folders
      description: 'Gets list of folders for the account '
      operationId: GetFolders
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/video/read
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
    post:
      tags:
        - Folders
      summary: Create Folder
      description: 'Create a new folder for the account '
      operationId: CreateFolder
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/video/create
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  '/accounts/{account_id}/folders/{folder_id}':
    get:
      tags:
        - Folders
      summary: Get Folder Information
      description: 'Gets information about a folder '
      operationId: GetFolderInformation
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/video/read
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
    patch:
      tags:
        - Folders
      summary: Update Folder Name
      description: 'Update the folder name '
      operationId: UpdateFolderName
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/video/update
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
    delete:
      tags:
        - Folders
      summary: Delete Folder
      description: 'Delete a folder '
      operationId: DeleteFolder
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/video/delete
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  '/accounts/{account_id}/folders/{folder_id}/videos':
    get:
      tags:
        - Folders
      summary: Get Videos in Folder
      description: 'Gets list of video objects in a folder '
      operationId: GetVideosInFolder
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/video/read
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  '/accounts/{account_id}/folders/{folder_id}/videos/{video_id}':
    put:
      tags:
        - Folders
      summary: Add Video to Folder
      description: 'Add a video to a folder '
      operationId: AddVideoToFolder
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/video/update
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
    delete:
      tags:
        - Folders
      summary: Remove Video from Folder
      description: 'Remove a video from a folder '
      operationId: RemoveVideoFromFolder
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/video/update
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  '/accounts/{account_id}/subscriptions':
    get:
      tags:
        - Notifications
      summary: Get Subscriptions List
      description: 'Get a list of all notification subscriptions for the account '
      operationId: GetSubscriptionsList
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/notifications/all
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
    post:
      tags:
        - Notifications
      summary: Create Subscription
      description: >-
        Establishes up to 10 endpoints that video changes should be sent to. Any
        change in video metadata will trigger a video change event and a
        notification &mdash; changes to assets used by the video will not
        trigger change events.
      operationId: CreateSubscription
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/notifications/all
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  '/accounts/{account_id}/subscriptions/{subscription_id}':
    get:
      tags:
        - Notifications
      summary: Get Subscription
      description: 'Get a notification subscription for the account '
      operationId: GetSubscription
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/notifications/all
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
    delete:
      tags:
        - Notifications
      summary: Delete Subscription
      description: 'Delete a notification subscription for the account '
      operationId: DeleteSubscription
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/notifications/all
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  '/accounts/{account_id}/videos/{video_id}/assets':
    get:
      tags:
        - Media Assets
      summary: Get Assets
      description: >-
        Gets assets for a given video. Note: you can use `/videos/ref:reference_id` instead of `/videos/video_id`
      operationId: GetAssets
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/video/read
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  '/accounts/{account_id}/videos/{video_id}/assets/dynamic_renditions':
    get:
      tags:
        - Media Assets
      summary: Get Dynamic Renditions
      description: >-
        Gets a list of dynamic renditions for a Dynamic Delivery video. Note:
        you can use `/videos/ref:reference_id` instead of `/videos/video_id`
      operationId: GetDynamicRenditions
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/video/read
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  '/accounts/{account_id}/videos/{video_id}/assets/renditions':
    get:
      tags:
        - Media Assets
      summary: Get Rendition List
      description: >-
        Gets a list of renditions for a given video. Notes: 1) this endpoint is
        for renditions created using the legacy ingest profiles - for Dynamic
        Deliver renditions, use the
        `/accounts/{account_id}/videos/{video_id}/assets/dynamic_renditions`
        endpoint; 2) you can use /videos/ref:reference_id instead of
        /videos/video_id
      operationId: GetRenditionList
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/video/read
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
    post:
      tags:
        - Media Assets
      summary: Add Rendition
      description: >-
        Add a remote rendition to the given video. Note: you can use
        `/videos/ref:reference_id` instead of `/videos/video_id`
      operationId: AddRendition
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/video/update
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  '/accounts/{account_id}/videos/{video_id}/assets/renditions/{asset_id}':
    get:
      tags:
        - Media Assets
      summary: Get Rendition
      description: >-
        Gets a specified rendition for a video. Note: you can use
        `/videos/ref:reference_id` instead of `/videos/video_id`
      operationId: GetRendition
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/video/read
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
    patch:
      tags:
        - Media Assets
      summary: Update Rendition
      description: >-
        Update the location for a remote rendition. Note: you can use
        `/videos/ref:reference_id` instead of `/videos/video_id`
      operationId: UpdateRendition
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/video/update
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
    delete:
      tags:
        - Media Assets
      summary: Delete Rendition
      description: >-
        Deletes a rendition for the given video. Note: this operation is only
        for remote renditions for remote asset videos &mdash; do not use it for
        renditions created by Video Cloud for ingested videos
      operationId: DeleteRendition
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/video/update
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  '/accounts/{account_id}/videos/{video_id}/assets/hls_manifest':
    get:
      tags:
        - Media Assets
      summary: Get HLS Manifest List
      description: >-
        Gets the hls_manifest for a given video. Notes: 1) you can use
        `/videos/ref:reference_id` instead of `/videos/video_id` 2) this method only
        returns a remote asset HTL manifest, not manifests for ingested videos
      operationId: GetHlsManifestList
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/video/read
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
    post:
      tags:
        - Media Assets
      summary: Add HLS Manifest
      description: >-
        Adds the location of an hls_manifest file for a remote asset. Note: you
        can use `/videos/ref:reference_id` instead of `/videos/video_id`
      operationId: AddHlsManifest
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/video/update
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  '/accounts/{account_id}/videos/{video_id}/assets/hls_manifest/{asset_id}':
    get:
      tags:
        - Media Assets
      summary: Get HLS Manifest
      description: >-
        Gets an hls_manifest for a given video. Note: you can use
        `/videos/ref:reference_id` instead of `/videos/video_id`
      operationId: GetHlsManifest
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/video/read
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
    patch:
      tags:
        - Media Assets
      summary: Update HLS Manifest
      description: >-
        Updates the location of a remote hls_manifest file for a remote asset.
        Note: you can use `/videos/ref:reference_id` instead of `/videos/video_id`
      operationId: UpdateHlsManifest
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/video/update
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
    delete:
      tags:
        - Media Assets
      summary: Delete HLS Manifest
      description: >-
        Deletes an hls_manifest file for a remote asset. Note: you can use
        `/videos/ref:reference_id` instead of `/videos/video_id`
      operationId: DeleteHlsManifest
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/video/update
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  '/accounts/{account_id}/videos/{video_id}/assets/dash_manifests':
    get:
      tags:
        - Media Assets
      summary: Get DASH Manifest List
      description: >-
        Gets the dash_manifests for a given video. Notes: 1. you can have
        multiple dash manifests with profiles; you can have only one dash
        manifest without a profile, but one manifest without a profile can be
        combined with multiple manifests with profiles; 2. all manifests
        intended to be used with the CMS API should include a profile - only
        DASH manifests with profiles will be returned by the CMS API &mdash;
        only a single DASH manifest without a profile will be returned by the
        Media API 3. you can use /videos/ref:reference_id instead of
        /videos/video_id
      operationId: GetDashManifestList
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/video/read
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
    post:
      tags:
        - Media Assets
      summary: Add DASH Manifest
      description: >-
        Adds a location for a remote DASH manifest Notes: 1. you can have
        multiple dash manifests with profiles; you can have only one dash
        manifest without a profile, but one manifest without a profile can be
        combined with multiple manifests with profiles; 2. all manifests
        intended to be used with the CMS API should include a profile - only
        DASH manifests with profiles will be returned by the CMS API &mdash;
        only a single DASH manifest without a profile will be returned by the
        Media API 3. you can use /videos/ref:reference_id instead of
        /videos/video_id
      operationId: AddDashManifest
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/video/update
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  '/accounts/{account_id}/videos/{video_id}/assets/dash_manifests/{asset_id}':
    get:
      tags:
        - Media Assets
      summary: Get DASH Manifest
      description: >-
        Gets a dash_manifest for a given video. Note: you can use
        `/videos/ref:reference_id` instead of `/videos/video_id`
      operationId: GetDashManifest
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/video/read
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
    patch:
      tags:
        - Media Assets
      summary: Update DASH Manifest
      description: >-
        Updates the location of a remote dash_manifest file for a remote asset.
        Note: you can use `/videos/ref:reference_id` instead of `/videos/video_id`
      operationId: UpdateDashManifest
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/video/update
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
    delete:
      tags:
        - Media Assets
      summary: Delete DASH Manifest
      description: >-
        Deletes an dash_manifest file for a remote asset. Note: you can use
        `/videos/ref:reference_id` instead of `/videos/video_id`
      operationId: DeleteDashManifest
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/video/update
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  '/accounts/{account_id}/videos/{video_id}/assets/hds_manifest':
    get:
      tags:
        - Media Assets
      summary: Get HDS Manifest List
      description: >-
        Gets the hds_manifest file for a given video. Note: you can use
        `/videos/ref:reference_id` instead of `/videos/video_id`
      operationId: GetHdsManifestList
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/video/read
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
    post:
      tags:
        - Media Assets
      summary: Add HDS Manifest
      description: >-
        Adds the location of an hds_manifest file for a remote asset. Note: you
        can use `/videos/ref:reference_id` instead of `/videos/video_id`
      operationId: AddHdsManifest
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/video/update
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  '/accounts/{account_id}/videos/{video_id}/assets/hds_manifest/{asset_id}':
    get:
      tags:
        - Media Assets
      summary: Get HDS Manifest
      description: >-
        Gets the hds_manifest file for a given video. Note: you can use
        `/videos/ref:reference_id` instead of `/videos/video_id`
      operationId: GetHdsManifest
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/video/read
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
    patch:
      tags:
        - Media Assets
      summary: Update HDS Manifest
      description: >-
        Updates the location of a remote hds_manifest file for a remote asset.
        Note: you can use `/videos/ref:reference_id` instead of `/videos/video_id`
      operationId: UpdateHdsManifest
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/video/update
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
    delete:
      tags:
        - Media Assets
      summary: Delete HDS Manifest
      description: >-
        Deletes an hds_manifest file for a remote asset. Note: you can use
        `/videos/ref:reference_id` instead of `/videos/video_id`
      operationId: DeleteHdsManifest
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/video/update
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  '/accounts/{account_id}/videos/{video_id}/assets/ism_manifest':
    get:
      tags:
        - Media Assets
      summary: Get ISM Manifest List
      description: >-
        Gets the ism_manifest for a given video. Note: you can use
        `/videos/ref:reference_id` instead of `/videos/video_id`
      operationId: GetIsmManifestList
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/video/read
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
    post:
      tags:
        - Media Assets
      summary: Add ISM Manifest
      description: >-
        Adds the location of an ism_manifest file for a remote asset. Note: you
        can use `/videos/ref:reference_id` instead of `/videos/video_id`
      operationId: AddIsmManifest
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/video/update
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  '/accounts/{account_id}/videos/{video_id}/assets/ism_manifest/{asset_id}':
    get:
      tags:
        - Media Assets
      summary: Get ISM Manifest
      description: >-
        Gets an ism_manifest for a given video. Note: you can use
        `/videos/ref:reference_id` instead of `/videos/video_id`
      operationId: GetIsmManifest
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/video/read
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
    patch:
      tags:
        - Media Assets
      summary: Update ISM Manifest
      description: >-
        Updates the location of a remote ism_manifest file for a remote asset.
        Note: you can use `/videos/ref:reference_id` instead of `/videos/video_id`
      operationId: UpdateIsmManifest
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/video/update
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
    delete:
      tags:
        - Media Assets
      summary: Delete ISM Manifest
      description: >-
        Deletes an ism_manifest file for a remote asset. Note: you can use
        `/videos/ref:reference_id` instead of `/videos/video_id`
      operationId: DeleteIsmManifest
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/video/update
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  '/accounts/{account_id}/videos/{video_id}/assets/ismc_manifest':
    get:
      tags:
        - Media Assets
      summary: Get ISMC Manifest List
      description: >-
        Gets the ismc_manifest files for a given video. Note: you can use
        `/videos/ref:reference_id` instead of `/videos/video_id`
      operationId: GetIsmcManifestList
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/video/read
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
    post:
      tags:
        - Media Assets
      summary: Add ISMC Manifest
      description: >-
        Adds the location of an ismc_manifest file for a remote asset. Note: you
        can use `/videos/ref:reference_id` instead of `/videos/video_id`
      operationId: AddIsmcManifest
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/video/update
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  '/accounts/{account_id}/videos/{video_id}/assets/ismc_manifest/{asset_id}':
    get:
      tags:
        - Media Assets
      summary: Get ISMC Manifest
      description: >-
        Gets the ismc_manifest file for a given video. Note: you can use
        `/videos/ref:reference_id` instead of `/videos/video_id`
      operationId: GetIsmcManifest
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/video/read
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
    patch:
      tags:
        - Media Assets
      summary: Update ISMC Manifest
      description: >-
        Updates the location of a remote ismc_manifest file for a remote asset.
        Note: you can use `/videos/ref:reference_id` instead of `/videos/video_id`
      operationId: UpdateIsmcManifest
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/video/update
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
    delete:
      tags:
        - Media Assets
      summary: Delete ISMC Manifest
      description: >-
        Deletes an ismc_manifest file for a remote asset. Note: you can use
        `/videos/ref:reference_id` instead of `/videos/video_id`
      operationId: DeleteIsmcManifest
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/video/update
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  '/accounts/{account_id}/videos/{video_id}/assets/poster':
    get:
      tags:
        - Legacy
      summary: Get Poster List
      description: >-
        Gets the poster file for a given video. Note that you can only add one
        poster for a video. Note: you can use /videos/ref:reference_id instead
        of /videos/video_id. **This request works for accounts on the legacy
        ingest system only - not supported for Dynamic Delivery**
      operationId: GetPosterList
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/video/read
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
    post:
      tags:
        - Legacy
      summary: Add Poster
      description: >-
        Adds a poster file for a remote asset. Ingested assets must be added via
        the Dynamic Ingest API. Note: you can use /videos/ref:reference_id
        instead of /videos/video_id. **This request works for accounts on the
        legacy ingest system only - not supported for Dynamic Delivery**
      operationId: AddPoster
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/video/update
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  '/accounts/{account_id}/videos/{video_id}/assets/poster/{asset_id}':
    get:
      tags:
        - Legacy
      summary: Get Poster
      description: >-
        Gets a poster file for a given video. Note that you can only add one
        poster for a video. Note: you can use /videos/ref:reference_id instead
        of /videos/video_id. **This request works for accounts on the legacy
        ingest system only - not supported for Dynamic Delivery**
      operationId: GetPoster
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/video/read
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
    patch:
      tags:
        - Legacy
      summary: Update Poster
      description: >-
        Updates the location of a remote poster file for a remote asset. Note:
        you can use `/videos/ref:reference_id` instead of `/videos/video_id`. **This
        request works for accounts on the legacy ingest system only - not
        supported for Dynamic Delivery**
      operationId: UpdatePoster
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/video/update
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
    delete:
      tags:
        - Legacy
      summary: Delete Poster
      description: >-
        Deletes a poster file for a remote asset. Note that you can only add one
        poster for a video. Note: you can use /videos/ref:reference_id instead
        of /videos/video_id. **This request works for accounts on the legacy
        ingest system only - not supported for Dynamic Delivery**
      operationId: DeletePoster
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/video/update
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  '/accounts/{account_id}/videos/{video_id}/assets/thumbnail':
    get:
      tags:
        - Legacy
      summary: Get Thumbnail List
      description: >-
        Gets the thumbnail for a given video. Note that you can only add one
        thumbnail for a video. Note: you can use `/videos/ref:reference_id`
        instead of `/videos/video_id`. **This request works for accounts on the
        legacy ingest system only - not supported for Dynamic Delivery**
      operationId: GetThumbnailList
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/video/read
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
    post:
      tags:
        - Legacy
      summary: Add_Thumbnail
      description: >-
        Adds a thumbnail file for a remote asset. Ingested assets must be added
        via the Dynamic Ingest API. Note: you can use /videos/ref:reference_id
        instead of /videos/video_id. **This request works for accounts on the
        legacy ingest system only - not supported for Dynamic Delivery**
      operationId: AddThumbnail
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/video/update
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  '/accounts/{account_id}/videos/{video_id}/assets/thumbnail/{asset_id}':
    get:
      tags:
        - Legacy
      summary: Get_Thumbnail
      description: >-
        Gets a thumbnail file for a given video. Note that you can only add one
        thumbnail for a video. Note: you can use /videos/ref:reference_id
        instead of /videos/video_id. **This request works for accounts on the
        legacy ingest system only - not supported for Dynamic Delivery**
      operationId: GetThumbnail
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/video/read
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
    patch:
      tags:
        - Legacy
      summary: Update_Thumbnail
      description: >-
        Updates the location of a remote thumbnail file for a remote asset.
        Note: you can use `/videos/ref:reference_id` instead of `/videos/video_id`.
        **This request works for accounts on the legacy ingest system only - not
        supported for Dynamic Delivery**
      operationId: UpdateThumbnail
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/video/read
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
    delete:
      tags:
        - Legacy
      summary: Delete_Thumbnail
      description: >-
        Deletes a thumbnail file for a remote asset. Note that you can only add
        one thumbnail for a video. Note: you can use /videos/ref:reference_id
        instead of /videos/video_id. **This request works for accounts on the
        legacy ingest system only - not supported for Dynamic Delivery**
      operationId: DeleteThumbnail
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/video/read
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  '/accounts/{account_id}/videos/{video_id}/assets/caption':
    get:
      tags:
        - Legacy
      summary: Get_Caption_List
      description: >-
        Gets the caption file for a given video (DFXP captions for the Smart
        Player). Note: 1) the caption endpoint is ONLY for working with DFXP
        captions used in the legacy Smart Player - WebVTT captions (text_tracks)
        for the new Brightcove Player are managed using the Update Video
        operation; 2) you can use /videos/ref:reference_id instead of
        /videos/video_id
      operationId: GetCaptionList
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/video/read
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
    post:
      tags:
        - Legacy
      summary: Add_Caption
      description: >-
        Adds a caption file for a remote asset (DFXP captions for the Smart
        Player). Note: 1) the caption endpoint is ONLY for working with DFXP
        captions used in the legacy Smart Player - WebVTT captions (text_tracks)
        for the new Brightcove Player are managed using the Update Video
        operation; 2) you can use /videos/ref:reference_id instead of
        /videos/video_id
      operationId: AddCaption
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/video/update
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  '/accounts/{account_id}/videos/{video_id}/assets/caption/{asset_id}':
    get:
      tags:
        - Legacy
      summary: Get_Caption
      description: >-
        Gets a caption file for a given video (DFXP captions for the Smart
        Player). Note: 1) the caption endpoint is ONLY for working with DFXP
        captions used in the legacy Smart Player - WebVTT captions (text_tracks)
        for the new Brightcove Player are managed using the Update Video
        operation; 2) you can use /videos/ref:reference_id instead of
        /videos/video_id
      operationId: GetCaption
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/video/read
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
    patch:
      tags:
        - Legacy
      summary: Update_Caption
      description: >-
        Updates the location of a remote caption file for a remote asset (DFXP
        captions for the Smart Player). Note: 1) the caption endpoint is ONLY
        for working with DFXP captions used in the legacy Smart Player - WebVTT
        captions (text_tracks) for the new Brightcove Player are managed using
        the Update Video operation; 2) you can use /videos/ref:reference_id
        instead of /videos/video_id
      operationId: UpdateCaption
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/video/update
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
    delete:
      tags:
        - Legacy
      summary: Delete_Caption
      description: >-
        Deletes a caption file for a remote asset (DFXP captions for the Smart
        Player). Note: 1) the caption endpoint is ONLY for working with DFXP
        captions used in the legacy Smart Player - WebVTT captions (text_tracks)
        for the new Brightcove Player are managed using the Update Video
        operation; 2) you can use /videos/ref:reference_id instead of
        /videos/video_id
      operationId: DeleteCaption
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/video/update
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
components:
  securitySchemes:
    BC_OAuth2:
      type: oauth2
      description: >-
        Brightcove OAuth API. See the [support
        documentation](https://support.brightcove.com/oauth-api) or [Getting
        Access
        Tokens](https://support.brightcove.com/oauth-api-sample-get-access-token)
        to learn more
      flows:
        clientCredentials:
          tokenUrl: 'https://oauth.brightcove.com/v4/access_token'
          scopes:
            video-cloud/video/read: Video Read
            video-cloud/video/create: Video Create
            video-cloud/video/update: Video Update
            video-cloud/video/delete: Video Delete
            video-cloud/video/all: Video ALL
            video-cloud/asset/delete: Digital Master Delete
            video-cloud/playlist/read: Playlist Read
            video-cloud/playlist/create: Playlist Create
            video-cloud/playlist/update: Playlist Update
            video-cloud/playlist/delete: Playlist Delete
            video-cloud/playlist/all: Playlist All
            video-cloud/sharing-relationships/read: Sharing Relationships Read
            video-cloud/sharing-relationships/create: Sharing Relationships Create
            video-cloud/sharing-relationships/update: Sharing Relationships Update
            video-cloud/sharing-relationships/delete: Sharing Relationships Delete
            video-cloud/sharing-relationships/all: Sharing Relationships All
            video-cloud/notifications/all: Notifications All
