var namespacecom_1_1ooyala_1_1android_1_1player_1_1exoplayer_1_1upstream =
[
    [ "OoyalaDrmHttpDataSource", "classcom_1_1ooyala_1_1android_1_1player_1_1exoplayer_1_1upstream_1_1_ooyala_drm_http_data_source.html", "classcom_1_1ooyala_1_1android_1_1player_1_1exoplayer_1_1upstream_1_1_ooyala_drm_http_data_source" ],
    [ "OoyalaDrmHttpDataSourceFactory", "classcom_1_1ooyala_1_1android_1_1player_1_1exoplayer_1_1upstream_1_1_ooyala_drm_http_data_source_factory.html", "classcom_1_1ooyala_1_1android_1_1player_1_1exoplayer_1_1upstream_1_1_ooyala_drm_http_data_source_factory" ]
];