var namespacecom_1_1ooyala_1_1android_1_1adobeanalyticssdk_1_1heartbeat =
[
    [ "OoyalaAdobeAnalyticsPluginDelegate", "classcom_1_1ooyala_1_1android_1_1adobeanalyticssdk_1_1heartbeat_1_1_ooyala_adobe_analytics_plugin_delegate.html", "classcom_1_1ooyala_1_1android_1_1adobeanalyticssdk_1_1heartbeat_1_1_ooyala_adobe_analytics_plugin_delegate" ],
    [ "OoyalaAdobeHeartbeatDelegate", "classcom_1_1ooyala_1_1android_1_1adobeanalyticssdk_1_1heartbeat_1_1_ooyala_adobe_heartbeat_delegate.html", "classcom_1_1ooyala_1_1android_1_1adobeanalyticssdk_1_1heartbeat_1_1_ooyala_adobe_heartbeat_delegate" ],
    [ "OoyalaAdobeHeartbeatPlayerPluginDelegate", "classcom_1_1ooyala_1_1android_1_1adobeanalyticssdk_1_1heartbeat_1_1_ooyala_adobe_heartbeat_player_plugin_delegate.html", "classcom_1_1ooyala_1_1android_1_1adobeanalyticssdk_1_1heartbeat_1_1_ooyala_adobe_heartbeat_player_plugin_delegate" ],
    [ "OoyalaAdobeHeartbeatPluginDelegate", "classcom_1_1ooyala_1_1android_1_1adobeanalyticssdk_1_1heartbeat_1_1_ooyala_adobe_heartbeat_plugin_delegate.html", "classcom_1_1ooyala_1_1android_1_1adobeanalyticssdk_1_1heartbeat_1_1_ooyala_adobe_heartbeat_plugin_delegate" ]
];