| Field                      | Type     | Description                                                                                                                                                                                        |
| -------------------------- | -------- | -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| name optional              | String   | video title        Size range: 1..255                                                                                                                                                              |
| description optional       | String   | video short description        Size range: ..250                                                                                                                                                   |
| economics optional         | String   | video short description        Default value: AD_SUPPORTED        Allowed values:          "AD_supported",          "FREE"                                                                         |
| ad_keys optional           | String   | string representing the ad key/value pairs assigned to the video. Key/value pairs are formatted as key=value and are separated by ampersands.        Default value: null        Size range: ..1800 |
| drm_disabled optional      | Boolean  | if>true will prevent this video from being DRM-protected (this field is only available for accounts enabled for Dynamic Delivery          and DRM)                                                 |
| long_description optional  | String   | video long description        Size range: ..5000                                                                                                                                                   |
| offline_enabled optional   | Boolean  | whether video is enabled for offline viewing (DRM-packaged videos only)        Default value: false                                                                                                |
| projection optional        | String   | Used for 360 video        Default value: null        Allowed values:          "equirectangular"                                                                                                    |
| reference_id optional      | String   | video reference-id (must be unique within the account)        Size range: ..150                                                                                                                    |
| state optional             | String   | state determines whether the video is playable or not        Default value: ACTIVE        Allowed values:          "ACTIVE",          "INACTIVE"                                                   |
| tags optional              | String[] | array>not contain commas        Default value: []                                                                                                                                                  |
| custom_fields optional     | Object   | map>Note: be sure to use the internal name for the field, not the display name        Default value: {}                                                                                            |
| cue_points optional        | Object[] | array of cue point maps        Default value: []                                                                                                                                                   |
| name optional              | String   | cue point name                                                                                                                                                                                     |
| type                       | String   | cue point type        Allowed values:          "AD",          "CODE"                                                                                                                               |
| time                       | Number   | time of the cue point in seconds; example: 10.527                                                                                                                                                  |
| metadata optional          | String   | optional metadata string (512 single-byte characters maximum)        Default value: null        Size range: ..512                                                                                  |
| force_stop optional        | Boolean  | whether video is force_stopped at the cue point        Default value: false                                                                                                                        |
| geo optional               | Object   | map of geo-filtering properties        Default value: {}                                                                                                                                           |
| countries optional         | String[] | array>ISO 3166 list of 2- or 4-letter codes in lower-case (search for "country codes")        Default value: null                                                                                  |
| exclude_countries optional | Boolean  | if true, country array is treated as a list of countries excluded from viewing        Default value: false                                                                                         |
| restricted optional        | Boolean  | whether geo-restriction is enabled for this video        Default value: false                                                                                                                      |
| link optional              | Object   | map of scheduling properties        Default value: {}                                                                                                                                              |
| text optional              | String   | text for the link        Size range: ..255                                                                                                                                                         |
| url optional               | Url      | URL for the link        Size range: ..250                                                                                                                                                          |
| published_at               | String   | ISO-8601 date-time string indicating when the video was published                                                                                                                                  |
| schedule optional          | Object   | map of scheduling properties        Default value: {}                                                                                                                                              |
| starts_at optional         | String   | start>ISO-8601 format        Default value: null                                                                                                                                                   |
| ends_at optional           | String   | end>ISO-8601 format        Default value: null                                                                                                                                                     |
| text_tracks optional       | Object[] | array>NOTE text_tracks are not>are settable otherwise, and can be used to add text tracks to ingested or remote asset videos        Default value: []                                              |
| src                        | String   | URL for the .vtt file                                                                                                                                                                              |
| kind optional              | String   | kind of text track        Allowed values:          "captions",          "chapters",          "subtitles",          "metadata"                                                                      |
| srclang                    | String   | 2-letter language code, such as "en" or "ko"                                                                                                                                                       |
| mime_type optional         | String   | mime-type for the track                                                                                                                                                                            |
| label optional             | String   | label for the track                                                                                                                                                                                |
| default optional           | Boolean  | whether this is the default track        Default value: false                                                                                                                                      |
